lessonsRaw['m18'] = {
  title:'数学进阶', icon:'🔢',
  data:[
    { type:'objective', items:[
      '掌握gcd/lcm的欧几里得算法（辗转相除法）',
      '掌握质数判断和埃筛、线性筛',
      '理解模运算及逆元的概念',
      '掌握快速幂的二进制分解思想',
      '掌握排列组合的公式和杨辉三角递推',
      '了解概率基础知识',
    ]},
    { type:'section', title:'1️⃣ 最大公约数与最小公倍数' },
    { type:'para', content:'最大公约数（gcd, Greatest Common Divisor）指能同时整除两个数的最大正整数。最小公倍数（lcm, Least Common Multiple）指能同时被两个数整除的最小正整数。' },
    { type:'sub', title:'欧几里得算法（辗转相除法）' },
    { type:'para', content:'欧几里得算法基于一个核心定理：gcd(a, b) = gcd(b, a mod b)。反复用余数代替大数，直到余数为0，此时的除数就是gcd。' },
    { type:'code', title:'欧几里得算法推导', content:'求 gcd(48, 18)：\n  48 ÷ 18 = 2 余 12  →  gcd(48,18) = gcd(18,12)\n  18 ÷ 12 = 1 余 6   →  gcd(18,12) = gcd(12,6)\n  12 ÷ 6 = 2 余 0    →  gcd(12,6) = 6\n所以 gcd(48, 18) = 6' },
    { type:'code', title:'gcd代码', content:'// 递归版\nint gcd(int a, int b) {\n    return b == 0 ? a : gcd(b, a % b);\n}\n\n// 迭代版\nint gcd(int a, int b) {\n    while (b) { int t = b; b = a % b; a = t; }\n    return a;\n}\n\n// lcm = a / gcd(a, b) * b  （先除后乘防溢出）\nint lcm(int a, int b) {\n    return a / gcd(a, b) * b;\n}' },
    { type:'tip', content:'求最小公倍数时一定要先除后乘：a / gcd(a, b) * b，避免 a * b 溢出 int 范围！' },

    { type:'section', title:'2️⃣ 质数判断与筛法' },
    { type:'para', content:'质数（素数）是指大于1且只能被1和自身整除的正整数。' },
    { type:'sub', title:'质数判断 — O(√n)' },
    { type:'para', content:'判断一个数n是否为质数，只需要检查 2 到 √n 之间的整数是否能整除n。因为如果n有大于√n的因子，必然对应一个小于√n的因子。' },
    { type:'code', title:'质数判断', content:'bool isPrime(int n) {\n    if (n < 2) return false;\n    for (int i = 2; i * i <= n; i++)\n        if (n % i == 0) return false;\n    return true;\n}' },
    { type:'sub', title:'埃拉托斯特尼筛法（埃筛）' },
    { type:'para', content:'埃筛的思想：从2开始，把每个质数的倍数全部标记为合数。复杂度 O(n log log n)。' },
    { type:'code', title:'埃筛', content:'vector<bool> isPrime(n + 1, true);\nisPrime[0] = isPrime[1] = false;\nfor (int i = 2; i * i <= n; i++) {\n    if (isPrime[i]) {\n        for (int j = i * i; j <= n; j += i)  // 从 i² 开始筛\n            isPrime[j] = false;\n    }\n}' },
    { type:'tip', content:'埃筛优化：从 i² 开始筛而不是从 2i 开始。因为 i 的较小倍数已经被更小的质数筛掉了。' },
    { type:'sub', title:'线性筛（欧拉筛）' },
    { type:'para', content:'线性筛在埃筛的基础上做了优化，保证每个合数只被它的最小质因子筛到一次，复杂度 O(n)。' },
    { type:'code', title:'线性筛', content:'vector<int> primes;\nvector<bool> isPrime(n + 1, true);\nisPrime[0] = isPrime[1] = false;\nfor (int i = 2; i <= n; i++) {\n    if (isPrime[i]) primes.push_back(i);\n    for (int p : primes) {\n        if (i * p > n) break;\n        isPrime[i * p] = false;\n        if (i % p == 0) break;  // p是i的最小质因子，保证每个合数只筛一次\n    }\n}' },
    { type:'table', headers:['对比','埃筛','线性筛'], rows:[
      ['复杂度','O(n log log n)','O(n)'],
      ['原理','每个质数筛其倍数','每个合数只被最小质因子筛一次'],
      ['优势','实现简单','严格线性，大范围（1e7+）更快'],
      ['劣势','合数可能被多次标记','实现稍复杂'],
    ]},

    { type:'section', title:'3️⃣ 模运算' },
    { type:'para', content:'模运算（mod）让你得到整数除法的余数。在竞赛中，当数字极大时，题目常常要求对 10⁹+7 取模。' },
    { type:'sub', title:'基本运算规则' },
    { type:'bullet', items:[
      '加法取模：(a + b) % M = ((a % M) + (b % M)) % M',
      '减法取模：(a - b) % M = ((a % M) - (b % M) + M) % M（注意加M避免负数）',
      '乘法取模：(a × b) % M = ((a % M) × (b % M)) % M',
      '幂运算取模：a^b % M 用快速幂（不能用pow先算再取模，会溢出）',
    ]},
    { type:'warning', content:'除法不能直接取模！a / b % M ≠ (a%M) / (b%M) % M。需要用到"逆元"的概念。' },
    { type:'sub', title:'逆元概念' },
    { type:'para', content:'逆元相当于模意义下的"倒数"。如果在模M下存在一个数 x 使得 b × x ≡ 1 (mod M)，则称 x 是 b 的逆元，记作 b⁻¹。这样 a / b mod M 就可以变成 a × b⁻¹ mod M。' },
    { type:'bullet', items:[
      '费马小定理（当 M 为质数）：a^(M-1) ≡ 1 (mod M) → a^(M-2) 就是 a 的逆元（用快速幂求）。',
      '扩展欧几里得算法：可以求任意互质的两个数的逆元。',
    ]},
    { type:'tip', content:'竞赛中最常见的模数是 10⁹+7（质数）。用快速幂求逆元：pow_mod(a, MOD-2, MOD)。' },

    { type:'section', title:'4️⃣ 快速幂' },
    { type:'para', content:'快速幂可以在 O(log n) 时间内计算 aⁿ mod M。核心思想是"二进制分解"——把指数n写成二进制形式，利用 a² = a×a, a⁴ = a²×a² 的倍增性质。' },
    { type:'sub', title:'二进制分解示例' },
    { type:'para', content:'计算 3¹³：13 的二进制是 1101 = 2³ + 2² + 2⁰ = 8 + 4 + 1。\n3¹³ = 3⁸ × 3⁴ × 3¹。' },
    { type:'code', title:'快速幂计算过程', content:'计算 3¹³ mod 100：\n\nn=13 (二进制 1101), base=3, ans=1\n\n第1位(1): ans = 1*3 = 3,  base = 3²=9,  n右移=6\n第2位(0): 跳过,            base = 9²=81, n右移=3\n第3位(1): ans = 3*81=243,  base = 81²→取模, n右移=1\n第4位(1): ans = 243*3=729%100=29, 结束\n\n3¹³ % 100 = 29' },
    { type:'code', title:'快速幂代码', content:'long long pow_mod(long long a, long long n, long long M) {\n    long long ans = 1 % M;\n    while (n) {\n        if (n & 1) ans = ans * a % M;  // 当前位为1\n        a = a * a % M;                 // 底数平方\n        n >>= 1;                       // 右移一位\n    }\n    return ans;\n}' },

    { type:'section', title:'5️⃣ 排列组合' },
    { type:'para', content:'排列组合是计数的基本工具，信奥赛中广泛应用（概率、DP计数、容斥等）。' },
    { type:'sub', title:'排列 P(n,k)' },
    { type:'para', content:'从n个不同元素中取出k个排成一列，顺序重要：P(n,k) = n! / (n-k)! = n × (n-1) × ... × (n-k+1)' },
    { type:'sub', title:'组合 C(n,k)' },
    { type:'para', content:'从n个不同元素中取出k个组成集合，顺序不重要：C(n,k) = n! / (k! × (n-k)!)' },
    { type:'table', headers:['公式','含义','示例'], rows:[
      ['C(n,0) = C(n,n) = 1','什么都不选 / 全选','C(5,0)=1, C(5,5)=1'],
      ['C(n,1) = n','选一个','C(5,1)=5'],
      ['C(n,k) = C(n, n-k)','对称性','C(5,2)=C(5,3)=10'],
      ['C(n,k) = C(n-1,k) + C(n-1,k-1)','杨辉三角递推','重要的DP公式！'],
    ]},
    { type:'sub', title:'杨辉三角' },
    { type:'para', content:'杨辉三角（帕斯卡三角）的每个数等于它上方两个数之和，正好对应 C(n,k) 的递推公式。' },
    { type:'code', title:'杨辉三角', content:'       1\n      1 1\n     1 2 1\n    1 3 3 1\n   1 4 6 4 1\n  1 5 10 10 5 1' },
    { type:'code', title:'杨辉三角递推求组合数', content:'// 预处理组合数 C[n][k]\nconst int MAXN = 1000;\nlong long C[MAXN+1][MAXN+1];\n\nfor (int i = 0; i <= MAXN; i++) {\n    C[i][0] = C[i][i] = 1;\n    for (int j = 1; j < i; j++)\n        C[i][j] = (C[i-1][j-1] + C[i-1][j]) % MOD;\n}' },
    { type:'tip', content:'C(n,k) 的值很快会溢出 int（如 C(34,17) ≈ 2.3×10⁹ 已经超 int 范围），一般需要取模或用 long long。' },

    { type:'section', title:'6️⃣ 概率基础' },
    { type:'para', content:'信奥赛中的概率问题通常围绕"古典概型"展开——所有可能结果等可能发生。' },
    { type:'sub', title:'基本概念' },
    { type:'bullet', items:[
      '样本空间：所有可能结果的集合。掷骰子的样本空间 = {1,2,3,4,5,6}。',
      '事件：样本空间的一个子集。如"掷出偶数点" = {2,4,6}。',
      '概率：P(事件) = 事件包含的结果数 / 总结果数。P(偶数点) = 3/6 = 1/2。',
      '互斥事件：不能同时发生的事件。P(A∪B) = P(A) + P(B)。',
      '独立事件：一个事件的发生不影响另一个。P(A∩B) = P(A) × P(B)。',
    ]},
    { type:'sub', title:'期望值' },
    { type:'para', content:'期望值（Expectation）是随机变量所有可能值的"加权平均"，即 E[X] = Σ (x × P(X=x))。' },
    { type:'code', title:'期望值计算示例', content:'掷一个骰子，点数的期望值：\nE = 1×(1/6) + 2×(1/6) + 3×(1/6) + 4×(1/6) + 5×(1/6) + 6×(1/6)\n  = (1+2+3+4+5+6)/6 = 21/6 = 3.5' },
    { type:'tip', content:'期望的线性性质非常重要：E[X+Y] = E[X] + E[Y]，即使X和Y不独立也成立！' },
    { type:'para', content:'在信奥赛中，概率常与DP结合——"概率DP"。状态是"某种情况下的期望值"，转移方程用期望的线性性质来推。' },

    { type:'section', title:'📌 常考题型' },
    { type:'quiz', items:[
      { q:'gcd(36, 24) 等于？', options:['12','6','4','8'], answer:0, explain:'36和24的最大公约数是12。' },
      { q:'线性筛中，i % p == 0 时为什么要 break？', options:['为了节省时间','保证每个合数只被最小质因子筛一次','p不是质数了','防止数组越界'], answer:1 },
      { q:'在模 M 下，a / b 的正确计算方式是？', options:['a % M / b % M','a × b⁻¹ % M','a × b % M','(a % M) / (b % M)'], answer:1, explain:'除法取模需要求逆元，a×b⁻¹ mod M。' },
      { q:'快速幂的复杂度是？', options:['O(log n)','O(n)','O(√n)','O(n log n)'], answer:0 },
      { q:'C(5,2) 等于？', options:['10','5','15','20'], answer:0, explain:'C(5,2) = 5!/(2!×3!) = 120/(2×6) = 10。或者杨辉三角第5行第3个数。' },
      { q:'掷两个骰子，点数之和的期望值是？', options:['6','7','3.5','8'], answer:1, explain:'两个骰子的期望都是3.5，E[X+Y] = E[X]+E[Y] = 3.5+3.5 = 7。' },
    ]},
  ]
};
