lessonsRaw['m17'] = {
  title:'图论基础', icon:'🔗',
  data:[
    { type:'objective', items:[
      '掌握Dijkstra算法的贪心思想和实现',
      '理解Floyd算法的动态规划思想和多源最短路',
      '掌握Kruskal算法（并查集实现最小生成树）',
      '了解Prim算法的过程',
      '理解拓扑排序的概念与入度法实现',
    ]},
    { type:'section', title:'1️⃣ 图的基本概念' },
    { type:'para', content:'图（Graph）由顶点（Vertex）和边（Edge）组成，记为 G = (V, E)。V是顶点集合，E是边集合。图论就是研究图的性质和算法的学科。' },
    { type:'table', headers:['概念','说明','例子'], rows:[
      ['有向图','边有方向，u→v和v→u不同','网页链接、地铁单行线'],
      ['无向图','边没有方向，u↔v','朋友关系、道路双行'],
      ['带权图','边上带有权重（距离、花费等）','地图导航中边的长度'],
      ['连通图','任意两点之间都有路径','一棵树是连通无环图'],
      ['度','一个顶点关联的边数','有向图分入度和出度'],
    ]},
    { type:'tip', content:'图的存储方式有两种：邻接矩阵（二维数组 O(n²) 空间）和邻接表（每个顶点的边列表 O(n+m) 空间）。竞赛中一般用邻接表。' },

    { type:'section', title:'2️⃣ Dijkstra——单源最短路' },
    { type:'para', content:'Dijkstra算法用于求从起点到所有其他点的最短路径，要求所有边权为非负数。其核心思想是"贪心"——每次选当前距离起点最近且未确定最短路的顶点，用它去更新其他顶点。' },
    { type:'sub', title:'算法步骤' },
    { type:'bullet', items:[
      '① 初始化：dis[s] = 0（起点到自身距离为0），其余dis[i] = ∞。用visited数组标记顶点是否已确定最短路。',
      '② 在未访问的顶点中，选dis值最小的顶点u。',
      '③ 对于u的每条出边(u→v, 权w)，若dis[u] + w < dis[v]，则更新dis[v] = dis[u] + w（这叫"松弛"操作）。',
      '④ 标记u为已访问。重复②~③直到所有顶点都被访问。',
      '⑤ 最终dis数组就是起点到每个顶点的最短距离。',
    ]},
    { type:'warning', content:'Dijkstra不能处理负权边！如果有负权边，要用SPFA或Bellman-Ford算法。NOIP中注意题目是否说明边权非负。' },
    { type:'sub', title:'手动模拟示例' },
    { type:'para', content:'图：有5个顶点（0~4），边如下（起点-终点-权重）：\n0→1 (4), 0→2 (2), 1→2 (1), 1→3 (5), 2→3 (8), 2→4 (10), 3→4 (2)' },
    { type:'para', content:'求从0出发到各点的最短路：' },
    { type:'table', headers:['步骤','选中顶点','dis[0]','dis[1]','dis[2]','dis[3]','dis[4]','说明'], rows:[
      ['初始','—','0','∞','∞','∞','∞','起点0'],
      ['1','0 ✓','0','4 (0+4)','2 (0+2)','∞','∞','从0更新1和2'],
      ['2','2 ✓','0','3 (2+1)','2','10 (2+8)','12 (2+10)','从2更新1、3、4'],
      ['3','1 ✓','0','3','2','8 (3+5)','12','从1更新3（3+5<10）'],
      ['4','3 ✓','0','3','2','8','10 (8+2)','从3更新4（8+2<12）'],
      ['5','4 ✓','0','3','2','8','10','完成'],
    ]},
    { type:'para', content:'最终最短路径：0→1=3（0→2→1），0→2=2，0→3=8（0→2→1→3），0→4=10（0→2→1→3→4）。' },
    { type:'code', title:'Dijkstra（堆优化）代码', content:'// 邻接表存图：vector<pair<int,int>> g[N]; // g[u] = {(v, w), ...}\nvector<int> dijkstra(int s, int n) {\n    vector<int> dis(n, INF);\n    vector<bool> vis(n, false);\n    dis[s] = 0;\n    // 小根堆：(距离, 顶点)\n    priority_queue<pair<int,int>, vector<...>, greater<...>> pq;\n    pq.push({0, s});\n    while (!pq.empty()) {\n        auto [d, u] = pq.top(); pq.pop();\n        if (vis[u]) continue;\n        vis[u] = true;\n        for (auto [v, w] : g[u]) {\n            if (dis[u] + w < dis[v]) {\n                dis[v] = dis[u] + w;\n                pq.push({dis[v], v});\n            }\n        }\n    }\n    return dis;\n}' },
    { type:'tip', content:'堆优化后复杂度 O((n+m)log n)，是竞赛中最常用的最短路算法。记住：一定要用 visited 跳过已确定最短路的顶点！' },

    { type:'section', title:'3️⃣ Floyd——多源最短路' },
    { type:'para', content:'Floyd算法可以求任意两点之间的最短路径，支持负权边（但不能有负环）。它的核心思想是"动态规划"——逐步允许经过更多中间点。' },
    { type:'sub', title:'算法思想' },
    { type:'bullet', items:[
      '状态：dis[k][i][j] 表示从i到j只允许经过编号≤k的中间点的最短路径长度。',
      '转移：dis[k][i][j] = min(dis[k-1][i][j], dis[k-1][i][k] + dis[k-1][k][j])',
      '解释：对于中间点k，要么不经过k（保持原值），要么经过k（i→k→j）。',
      '优化后直接用二维数组 dis[i][j]，三重循环 k→i→j。',
    ]},
    { type:'code', title:'Floyd算法代码', content:'int dis[N][N];\n// 初始化：dis[i][i] = 0, 有边 dis[i][j] = w, 无边 dis[i][j] = INF\nfor (int k = 0; k < n; k++)\n    for (int i = 0; i < n; i++)\n        for (int j = 0; j < n; j++)\n            if (dis[i][k] + dis[k][j] < dis[i][j])\n                dis[i][j] = dis[i][k] + dis[k][j];\n// 最终 dis[i][j] 为 i 到 j 的最短距离' },
    { type:'tip', content:'Floyd的复杂度是 O(n³)，n一般不超过500时才可用。三重循环的顺序必须是 k→i→j，不能变！' },
    { type:'table', headers:['对比','Dijkstra','Floyd'], rows:[
      ['用途','单源最短路','多源最短路（任意两点）'],
      ['算法思想','贪心','动态规划'],
      ['复杂度','O((n+m)log n)','O(n³)'],
      ['适用范围','n可到10⁵+','n ≤ 500'],
      ['负权边','不支持','支持（不能有负环）'],
    ]},

    { type:'section', title:'4️⃣ Kruskal——最小生成树' },
    { type:'para', content:'Kruskal算法用于求图的最小生成树（MST）。最小生成树是用n-1条边把n个顶点连通且边权和最小的树。Kruskal的核心是"贪心+并查集"。' },
    { type:'sub', title:'算法步骤' },
    { type:'bullet', items:[
      '① 将所有边按权值从小到大排序。',
      '② 从权值最小的边开始，逐条尝试加入：',
      '   - 如果该边的两个顶点尚未连通（不在同一个集合中），则加入这条边。',
      '   - 如果已经连通，则跳过（加入会形成环）。',
      '③ 重复②直到选出 n-1 条边，或者所有边都尝试完。',
    ]},
    { type:'code', title:'Kruskal算法代码', content:'struct Edge { int u, v, w; };\nvector<Edge> edges;\nsort(edges.begin(), edges.end(), [](Edge a, Edge b){ return a.w < b.w; });\n\nint ans = 0, cnt = 0; // cnt: 已选边数\nfor (auto [u, v, w] : edges) {\n    if (find(u) != find(v)) {  // u和v不在同一集合\n        unite(u, v);           // 合并\n        ans += w;\n        cnt++;\n        if (cnt == n-1) break; // 已够n-1条边\n    }\n}\n// ans 为最小生成树的权值和' },
    { type:'sub', title:'并查集实现' },
    { type:'code', title:'并查集（Union-Find）', content:'int parent[N];\nvoid init(int n) { for (int i = 0; i < n; i++) parent[i] = i; }\n\nint find(int x) {\n    if (parent[x] != x) parent[x] = find(parent[x]); // 路径压缩\n    return parent[x];\n}\n\nvoid unite(int x, int y) {\n    int rx = find(x), ry = find(y);\n    if (rx != ry) parent[rx] = ry;\n}' },
    { type:'tip', content:'Kruskal的时间复杂度为 O(m log m)（主要是排序的代价），适合边数较少（稀疏图）的情况。' },

    { type:'section', title:'5️⃣ Prim——最小生成树' },
    { type:'para', content:'Prim算法是另一种求最小生成树的贪心算法，与Dijkstra非常相似，但Dijkstra累积"到起点的距离"，Prim累积"到已选集合的距离"。' },
    { type:'sub', title:'算法步骤' },
    { type:'bullet', items:[
      '① 任选一个起点加入MST集合。',
      '② 维护数组 dis[i] 表示顶点i到MST集合的最短距离。',
      '③ 每次选dis值最小的未加入顶点加入MST，并用它的边更新其他未加入顶点的dis值。',
      '④ 重复③直到所有顶点加入MST。',
    ]},
    { type:'code', title:'Prim算法代码', content:'int prim(int s, int n) {\n    vector<int> dis(n, INF);\n    vector<bool> vis(n, false);\n    dis[s] = 0;\n    int ans = 0;\n    for (int i = 0; i < n; i++) {\n        int u = -1;\n        for (int j = 0; j < n; j++)\n            if (!vis[j] && (u == -1 || dis[j] < dis[u]))\n                u = j;\n        if (dis[u] == INF) return -1; // 不连通\n        vis[u] = true;\n        ans += dis[u];\n        for (auto [v, w] : g[u])\n            if (!vis[v] && w < dis[v])\n                dis[v] = w;\n    }\n    return ans;\n}' },
    { type:'table', headers:['对比','Kruskal','Prim'], rows:[
      ['核心操作','排序边 → 并查集合并','找最小dis → 加入 → 更新邻居'],
      ['复杂度','O(m log m)','O(n²) 或 O(m log n)（堆优化）'],
      ['适用场景','稀疏图（m少）','稠密图（n小m大）'],
      ['数据结构','并查集','优先队列（堆优化）'],
    ]},

    { type:'section', title:'6️⃣ 拓扑排序' },
    { type:'para', content:'拓扑排序是对有向无环图（DAG）的顶点进行排序，使得对每一条有向边 u→v，u 都在 v 的前面。拓扑排序的应用：任务调度、课程安排（先修课关系）、编译依赖分析。' },
    { type:'sub', title:'入度法（Kahn算法）' },
    { type:'bullet', items:[
      '① 计算每个顶点的入度（有多少条边指向它）。',
      '② 把所有入度为0的顶点入队列（这些顶点没有前置依赖）。',
      '③ 弹出队首顶点u，输出u；对于u的每个后继v，将v的入度减1。',
      '④ 如果v的入度变为0，把v入队。',
      '⑤ 重复③~④直到队列为空。',
      '⑥ 如果输出的顶点数 < 总顶点数，说明图中存在环（无法拓扑排序）。',
    ]},
    { type:'code', title:'拓扑排序（Kahn算法）', content:'vector<int> topoSort(int n, vector<int> g[]) {\n    vector<int> indeg(n, 0), ans;\n    for (int u = 0; u < n; u++)\n        for (int v : g[u]) indeg[v]++;\n    \n    queue<int> q;\n    for (int i = 0; i < n; i++)\n        if (indeg[i] == 0) q.push(i);\n    \n    while (!q.empty()) {\n        int u = q.front(); q.pop();\n        ans.push_back(u);\n        for (int v : g[u])\n            if (--indeg[v] == 0) q.push(v);\n    }\n    \n    if (ans.size() != n) return {}; // 有环\n    return ans;\n}' },
    { type:'tip', content:'拓扑排序也可以DFS实现（记录每个顶点的"访问状态"：0未访问、1访问中、2已访问。如果在DFS中遇到状态1的顶点，说明有环）。' },

    { type:'section', title:'📌 常考题型' },
    { type:'quiz', items:[
      { q:'Dijkstra算法不能处理以下哪种情况？', options:['无向图','带权图','负权边','非连通图'], answer:2, explain:'Dijkstra基于贪心，负权边会破坏贪心的正确性。' },
      { q:'Floyd算法的三重循环顺序是？', options:['i→j→k','k→i→j','i→k→j','j→k→i'], answer:1, explain:'最外层是中间顶点k，然后i和j。这个顺序不能改变！' },
      { q:'Kruskal算法中用来检测环的数据结构是？', options:['栈','队列','并查集','堆'], answer:2 },
      { q:'拓扑排序能处理什么类型的图？', options:['有向带环图','无向图','有向无环图（DAG）','任意图'], answer:2 },
      { q:'Prim算法与以下哪个算法最相似？', options:['Floyd','Kruskal','Dijkstra','Bellman-Ford'], answer:2, explain:'Prim和Dijkstra都用了"选最小+更新邻居"的贪心框架。' },
      { q:'如果Kahn算法输出的顶点数小于总顶点数，说明？', options:['图中有孤立点','图中有环','图不连通','有顶点入度为负'], answer:1, explain:'剩余顶点的入度都不为0，说明存在环。' },
    ]},
  ]
};
