lessonsRaw['m16'] = {
  title:'动态规划', icon:'📊',
  data:[
    { type:'objective', items:[
      '理解动态规划（DP）三要素：状态定义、转移方程、初始条件',
      '掌握01背包问题的状态转移表推导过程',
      '区分完全背包与01背包的区别',
      '掌握最长上升子序列（LIS）的DP解法',
      '掌握最长公共子序列（LCS）的DP解法',
      '了解区间DP的基本思想',
    ]},
    { type:'section', title:'1️⃣ 动态规划思想' },
    { type:'para', content:'动态规划（Dynamic Programming，简称DP）是一种把原问题分解成相互重叠的子问题，通过求解子问题并记录结果来避免重复计算的方法。"动态"是指状态在变化，"规划"是指在每一步作出最优决策。' },
    { type:'tip', content:'DP的核心：用空间换时间。如果一道题有"最优子结构"和"重叠子问题"两个特征，就可以考虑用DP。' },
    { type:'sub', title:'DP三要素' },
    { type:'bullet', items:[
      '① 状态定义：定义 dp[i][j] 或 dp[i] 表示什么。状态定义的好坏直接决定能否写出转移方程。',
      '② 转移方程：描述如何从一个或多个子状态推导出当前状态，即 dp[i] = f(dp[i-1], dp[i-2], ...)。',
      '③ 初始条件：最小的子问题（边界）如何定义。例如 dp[0] = 0。',
    ]},
    { type:'tip', content:'DP解题模板：\n1. 确定状态定义\n2. 写出转移方程\n3. 设置初始条件\n4. 按某种顺序（通常是正序或倒序）计算所有状态\n5. 从最终状态中获取答案' },

    { type:'section', title:'2️⃣ 01背包问题' },
    { type:'para', content:'01背包是最经典的DP入门问题：有N个物品，每个物品有重量w[i]和价值v[i]，背包容量为C。每个物品最多选一次（取0或1），求能装入的最大总价值。' },
    { type:'code', title:'01背包问题描述', content:'输入：\n  N = 4（物品数量），C = 5（背包容量）\n  物品1: 重量=2, 价值=3\n  物品2: 重量=1, 价值=2\n  物品3: 重量=3, 价值=4\n  物品4: 重量=2, 价值=2\n\n求：背包能装下的最大总价值？' },
    { type:'sub', title:'状态定义与转移方程' },
    { type:'bullet', items:[
      '状态定义：dp[i][j] 表示"考虑前i个物品，背包容量为j时能获得的最大价值"。',
      '转移方程：dp[i][j] = max(dp[i-1][j], dp[i-1][j-w[i]] + v[i])',
      '  解释：第i个物品要么不选（继承dp[i-1][j]），要么选（前提j≥w[i]时，价值=dp[i-1][j-w[i]] + v[i]）。',
      '初始条件：dp[0][j] = 0（一个物品都不考虑时价值为0）。',
    ]},
    { type:'sub', title:'dp表格填充过程（逐步演示）' },
    { type:'para', content:'初始状态：dp[0][*] = 0。下面通过物品逐一填表。' },
    { type:'para', content:'🗃️ 第1件物品（w=2, v=3）：' },
    { type:'table', headers:['i\\j','0','1','2','3','4','5'], rows:[
      ['0（无物品）','0','0','0','0','0','0'],
      ['1（物品1）','0','0','3','3','3','3'],
    ]},
    { type:'para', content:'解释：容量j=0或1时放不下物品1（w=2），所以值为0。j≥2时放得下，价值=3。' },
    { type:'para', content:'🗃️ 第2件物品（w=1, v=2）：' },
    { type:'table', headers:['i\\j','0','1','2','3','4','5'], rows:[
      ['0','0','0','0','0','0','0'],
      ['1','0','0','3','3','3','3'],
      ['2','0','2','3','5','5','5'],
    ]},
    { type:'para', content:'解释：dp[2][1] = max(dp[1][1]=0, dp[1][0]+2=0+2=2) = 2。\ndp[2][3] = max(dp[1][3]=3, dp[1][2]+2=3+2=5) = 5（选物品2+物品1）。' },
    { type:'para', content:'🗃️ 第3件物品（w=3, v=4）：' },
    { type:'table', headers:['i\\j','0','1','2','3','4','5'], rows:[
      ['0','0','0','0','0','0','0'],
      ['1','0','0','3','3','3','3'],
      ['2','0','2','3','5','5','5'],
      ['3','0','2','3','5','5','7'],
    ]},
    { type:'para', content:'解释：dp[3][5] = max(dp[2][5]=5, dp[2][2]+4=3+4=7) = 7（选物品1+物品3）。' },
    { type:'para', content:'🗃️ 第4件物品（w=2, v=2）：' },
    { type:'table', headers:['i\\j','0','1','2','3','4','5'], rows:[
      ['0','0','0','0','0','0','0'],
      ['1','0','0','3','3','3','3'],
      ['2','0','2','3','5','5','5'],
      ['3','0','2','3','5','5','7'],
      ['4','0','2','3','5','5','7'],
    ]},
    { type:'para', content:'最终答案：dp[4][5] = 7。最优方案为选物品1（w=2,v=3）和物品3（w=3,v=4），总重量=5，总价值=7。' },
    { type:'code', title:'01背包核心代码', content:'int dp[N+1][C+1];\nfor (int i = 1; i <= N; i++) {\n    for (int j = 0; j <= C; j++) {\n        dp[i][j] = dp[i-1][j]; // 不选\n        if (j >= w[i])\n            dp[i][j] = max(dp[i][j], dp[i-1][j-w[i]] + v[i]);\n    }\n}\n// 答案: dp[N][C]' },
    { type:'tip', content:'空间优化：可以用一维数组 dp[j]，但内层 j 必须倒序遍历（从C到0），避免一个物品被多次选取。' },

    { type:'section', title:'3️⃣ 完全背包 vs 01背包' },
    { type:'para', content:'完全背包问题：每种物品有无限多个，可以重复选择。与01背包的唯一区别就在这里。' },
    { type:'table', headers:['对比项','01背包','完全背包'], rows:[
      ['每种物品可选的次数','最多1次','无限次'],
      ['转移方程','dp[i][j] = max(dp[i-1][j], dp[i-1][j-w[i]] + v[i])','dp[i][j] = max(dp[i-1][j], dp[i][j-w[i]] + v[i])'],
      ['一维数组内层循环','倒序（j从C到0）','正序（j从0到C）'],
      ['典型例题','选或不选唯一','硬币找零（无限硬币）'],
    ]},
    { type:'para', content:'关键区别：01背包的"选"依赖于dp[i-1][...]（上一行），完全背包的"选"依赖于dp[i][...]（同一行），因为选了之后还可以再选。' },
    { type:'code', title:'完全背包一维代码', content:'int dp[C+1] = {0};\nfor (int i = 1; i <= N; i++) {\n    for (int j = w[i]; j <= C; j++) { // 注意：正序！\n        dp[j] = max(dp[j], dp[j-w[i]] + v[i]);\n    }\n}' },

    { type:'section', title:'4️⃣ 最长上升子序列（LIS）' },
    { type:'para', content:'给定一个序列，求其中最长的严格递增子序列的长度。子序列不要求连续，但元素的相对顺序不变。' },
    { type:'code', title:'LIS问题举例', content:'序列:  [10, 9, 2, 5, 3, 7, 101, 18]\nLIS:   [2, 5, 7, 101] 或 [2, 3, 7, 101] → 长度 = 4' },
    { type:'sub', title:'O(n²) DP解法' },
    { type:'bullet', items:[
      '状态：dp[i] 表示以 a[i] 结尾的最长上升子序列长度。',
      '转移：dp[i] = max(dp[j] + 1) 其中 0 ≤ j < i 且 a[j] < a[i]',
      '初始：dp[i] = 1（至少包含自己）',
      '答案：max(dp[i])',
    ]},
    { type:'code', title:'LIS O(n²) 代码', content:'int LIS(vector<int>& a) {\n    int n = a.size(), ans = 1;\n    vector<int> dp(n, 1);\n    for (int i = 0; i < n; i++) {\n        for (int j = 0; j < i; j++) {\n            if (a[j] < a[i])\n                dp[i] = max(dp[i], dp[j] + 1);\n        }\n        ans = max(ans, dp[i]);\n    }\n    return ans;\n}' },
    { type:'tip', content:'还有 O(n log n) 的优化方法（维护单调递增数组+二分查找），是NOIP常考知识点，建议掌握！' },

    { type:'section', title:'5️⃣ 最长公共子序列（LCS）' },
    { type:'para', content:'给定两个字符串（或序列），求它们的最长公共子序列的长度。' },
    { type:'code', title:'LCS问题举例', content:'字符串A: "ABCBDAB"\n字符串B: "BDCAB"\nLCS: "BCAB" 或 "BCBA" → 长度 = 4' },
    { type:'sub', title:'状态定义与转移方程' },
    { type:'bullet', items:[
      '状态：dp[i][j] 表示 A[0..i-1] 和 B[0..j-1] 的LCS长度。',
      '转移：若 A[i-1] == B[j-1]，则 dp[i][j] = dp[i-1][j-1] + 1；\n      否则 dp[i][j] = max(dp[i-1][j], dp[i][j-1])。',
      '初始：dp[0][j] = dp[i][0] = 0。',
    ]},
    { type:'sub', title:'dp表格示例' },
    { type:'para', content:'A="ABC", B="ACB" 的LCS表格：' },
    { type:'table', headers:['dp','(空)','A','C','B'], rows:[
      ['(空)','0','0','0','0'],
      ['A','0','1','1','1'],
      ['B','0','1','1','2'],
      ['C','0','1','2','2'],
    ]},
    { type:'para', content:'解释：dp[3][3] = 2（LCS="AB"或"AC"，长度为2）。当字符相等时（如A=A），取左上+1；不等时取左边或上边的较大值。' },
    { type:'code', title:'LCS代码', content:'int LCS(string A, string B) {\n    int n = A.size(), m = B.size();\n    vector<vector<int>> dp(n+1, vector<int>(m+1, 0));\n    for (int i = 1; i <= n; i++) {\n        for (int j = 1; j <= m; j++) {\n            if (A[i-1] == B[j-1])\n                dp[i][j] = dp[i-1][j-1] + 1;\n            else\n                dp[i][j] = max(dp[i-1][j], dp[i][j-1]);\n        }\n    }\n    return dp[n][m];\n}' },

    { type:'section', title:'6️⃣ 区间DP简介' },
    { type:'para', content:'区间DP是一种以"区间"为状态的DP。核心思想：大区间的最优解由内部小区间的最优解合并得到。' },
    { type:'bullet', items:[
      '状态定义：dp[l][r] 表示区间 [l, r] 上的最优值。',
      '转移方式：枚举分割点k，将区间 [l, r] 拆成 [l, k] 和 [k+1, r]。',
      '计算顺序：按区间长度从小到大计算（先算length=1，再length=2...）。',
    ]},
    { type:'sub', title:'经典例题：石子合并' },
    { type:'para', content:'N堆石子排成一排，每次可以合并相邻两堆，花费为两堆石子数量之和。求把所有石子合并成一堆的最小总花费。' },
    { type:'code', title:'石子合并（区间DP）', content:'输入: 石子堆 [4, 1, 1, 4]\n\n区间DP表格（合并最小花费）：\n\n长度=1: dp[i][i] = 0 （单堆不需要合并）\n\n长度=2:\n  dp[1][2] = 4+1 = 5\n  dp[2][3] = 1+1 = 2\n  dp[3][4] = 1+4 = 5\n\n长度=3:\n  dp[1][3] = min(dp[1][2]+dp[3][3], dp[1][1]+dp[2][3]) + sum(1..3)\n           = min(5+0, 0+2) + 6 = 2 + 6 = 8\n\n长度=4:\n  dp[1][4] = min(\n    dp[1][1]+dp[2][4],\n    dp[1][2]+dp[3][4],\n    dp[1][3]+dp[4][4]\n  ) + sum(1..4)' },
    { type:'code', title:'区间DP通用模板', content:'int n, a[N], sum[N], dp[N][N];\nmemset(dp, 0x3f, sizeof(dp)); // 初始化为无穷大\nfor (int i = 1; i <= n; i++) dp[i][i] = 0;\n\nfor (int len = 2; len <= n; len++) {          // 区间长度\n    for (int l = 1; l + len - 1 <= n; l++) {   // 左端点\n        int r = l + len - 1;                   // 右端点\n        for (int k = l; k < r; k++) {          // 分割点\n            dp[l][r] = min(dp[l][r], dp[l][k] + dp[k+1][r] + sum[r] - sum[l-1]);\n        }\n    }\n}\n// 答案: dp[1][n]' },
    { type:'tip', content:'区间DP的特征：问题可以分解成相邻子区间的合并问题。常见的还有括号匹配、多边形三角剖分等。' },

    { type:'section', title:'📌 常考题型' },
    { type:'quiz', items:[
      { q:'下列哪个不属于动态规划的三要素？', options:['状态定义','转移方程','贪心策略','初始条件'], answer:2, explain:'DP三要素：状态定义、转移方程、初始条件。贪心是另一种算法思想。' },
      { q:'01背包一维优化时，内层循环为什么要倒序？', options:['为了节省时间','防止物品被重复选择','为了从大到小计算','没有特殊原因'], answer:1, explain:'倒序遍历保证 dp[j-w[i]] 来自上一行，即每个物品最多选一次。' },
      { q:'完全背包与01背包在一维实现上的核心区别是？', options:['外层循环顺序不同','内层循环方向不同','物品数量不同','重量限制不同'], answer:1 },
      { q:'最长上升子序列（LIS）的 O(n²) DP解法中，dp[i] 的含义是？', options:['前i个元素的LIS长度','以a[i]结尾的LIS长度','a[i]之前的LIS长度','全局LIS长度'], answer:1 },
      { q:'LCS的状态转移中，当 A[i-1] != B[j-1] 时，dp[i][j] 等于？', options:['0','dp[i-1][j-1]','max(dp[i-1][j], dp[i][j-1])','min(dp[i-1][j], dp[i][j-1])'], answer:2 },
      { q:'区间DP的计算顺序一般是？', options:['从小到大','按区间长度从小到大','按区间长度从大到小','随机顺序'], answer:1, explain:'先算长度小的区间，逐步合并成大的。' },
    ]},
  ]
};
