// 模块10：指针·引用·结构体
lessonsRaw['m10'] = {
  title: '指针·引用·结构体',
  icon: '📍',
  data: [
    { type:'objective', items:[
      '理解指针的概念：内存地址、取地址(&)和解引用(*)',
      '掌握指针与数组、字符串的关系',
      '能区分 NULL 指针、野指针与悬空指针',
      '理解引用的概念及其与指针的区别',
      '学会定义和使用 struct 结构体',
      '了解 union 联合体的内存布局',
    ]},

    { type:'section', title:'1️⃣ 内存地址与指针基础' },
    { type:'para', content:'程序运行时，变量存储在内存中。每个内存单元（通常是1字节）都有一个独一无二的编号，这个编号就是内存地址。指针就是用来存储这些地址的变量。' },
    { type:'code', title:'声明与使用指针', content:'int x = 10;\nint* p = &x;   // p存储了x的地址\n\ncout << p << endl;   // 输出地址（如 0x7ffee1234）\ncout << *p << endl;  // 输出10——通过地址访问x的值（解引用）\ncout << &x << endl;  // 输出x的地址，和p一样\n\n*p = 20;             // 通过指针修改x\ncout << x << endl;   // 输出20' },
    { type:'bullet', items:[
      '&：取地址运算符，获取变量的内存地址',
      '*：解引用运算符/间接访问符，通过地址访问存储的值',
      '声明 int* p 意思是"p是一个指向int类型的指针变量"',
      '指针本身也占用内存（64位系统上固定8字节）',
      'int *p、int* p、int * p 写法都合法，推荐 int* p',
    ]},
    { type:'tip', content:'指针的两种"身份"：声明时带*表示"这是一个指针类型"；使用时带*表示"对指针解引用"。初学者常弄混，拿代码试几次就好了。' },
    { type:'sub', title:'指针的大小' },
    { type:'table', headers:['系统位数','指针大小（所有类型）','说明'], rows:[
      ['32位','4 字节','地址用32位二进制数表示，最大4GB内存'],
      ['64位','8 字节','地址用64位二进制数表示，远超32位寻址范围'],
    ]},
    { type:'warning', content:'信奥赛考点：无论 int* 还是 char*，同一系统上所有指针大小相同（都是地址，长度由系统位数决定）。64位系统上所有指针都是8字节！' },

    { type:'section', title:'2️⃣ 指针的运算' },
    { type:'para', content:'指针支持加减运算，但加减的单位不是字节，而是"所指向类型的大小"。' },
    { type:'code', title:'指针加减的含义', content:'int arr[5] = {10, 20, 30, 40, 50};\nint* p = arr;      // p指向arr[0]\n\ncout << *p << endl;       // 10\np++;                      // p前进一个int（4字节）\ncout << *p << endl;       // 20（arr[1]）\n\ncout << *(p + 2) << endl; // 40（arr[3]）\n\n// 遍历数组\nfor (int* p = arr; p < arr + 5; p++) {\n    cout << *p << " ";\n}\n// 输出：10 20 30 40 50' },
    { type:'bullet', items:[
      'p + n 等价于地址增加 n * sizeof(类型) 字节',
      '两个指针相减 = 两个地址之间跨越的元素个数（不是字节数）',
      '指针可以比较大小（<, >, ==）——按地址数值比较',
    ]},

    { type:'section', title:'3️⃣ 指针与数组' },
    { type:'para', content:'在C++中，数组名本质上就是一个指向数组首元素的常量指针。' },
    { type:'code', title:'数组名 == 指针', content:'int arr[5] = {2, 4, 6, 8, 10};\n\n// 以下三种写法完全等价：\ncout << arr[2] << endl;     // 6\ncout << *(arr + 2) << endl; // 6\ncout << *(2 + arr) << endl; // 6（满足交换律）\n\n// 区别：arr是常量指针，不能修改\n// arr++ ❌ 错误！\nint* p = arr;\np++;  // ✅ 可以，p指向arr[1]' },
    { type:'tip', content:'a[i] 在C++内部等价于 *(a + i)。所以 2[arr] 这种"奇怪"的写法也是合法的——因为 2[arr] 等价于 *(2 + arr) = *(arr + 2) = arr[2]。' },
    { type:'sub', title:'指针数组 vs 数组指针' },
    { type:'table', headers:['写法','名称','含义'], rows:[
      ['int* p[5]','指针数组','一个数组，每个元素都是 int* 指针'],
      ['int (*p)[5]','数组指针','一个指针，指向包含5个int的数组'],
    ]},
    { type:'warning', content:'C++后缀运算符[]优先级高于前缀运算符*。int* p[5] => 先形成数组，再取指针。int (*p)[5] => 括号优先，p先被声明为指针。考试常考区别！' },

    { type:'section', title:'4️⃣ NULL指针、野指针与悬空指针' },
    { type:'sub', title:'NULL指针（空指针）' },
    { type:'para', content:'不指向任何有效对象的指针。C++11起推荐用 nullptr 而非 NULL。' },
    { type:'code', title:'空指针', content:'int* p = nullptr;  // C++11推荐\nint* q = NULL;      // 传统写法（本质是整数0）\n\nif (p == nullptr) {\n    cout << "p是空指针" << endl;\n}\n\n// 对空指针解引用会导致程序崩溃\n// *p = 10;  ❌ 段错误！' },
    { type:'sub', title:'野指针' },
    { type:'para', content:'指针变量未初始化，其值是随机的（指向未知的内存地址）。使用野指针极度危险。' },
    { type:'code', title:'野指针示例', content:'int* p;          // 未初始化，野指针\n*p = 10;         // ❌ 往随机地址写数据，可能崩\n\n// 解决方法：声明时初始化\nint* p = nullptr;\nint* q = &someVar;' },
    { type:'sub', title:'悬空指针（Dangling Pointer）' },
    { type:'para', content:'指针指向的内存已经被释放（free/delete）了，但指针的值没有清空。' },
    { type:'code', title:'悬空指针', content:'int* p = new int(42);\ndelete p;          // 内存被释放\n// p变成了悬空指针\n*p = 100;          // ❌ 访问已释放的内存，未定义行为\np = nullptr;       // ✅ 释放后立即置空是好习惯' },
    { type:'warning', content:'笔试常考：野指针是"未初始化"导致，悬空指针是"释放后未置空"导致。两者都是未定义行为（UB），必须避免！' },

    { type:'section', title:'5️⃣ 指针与函数' },
    { type:'sub', title:'指针作为函数参数（传址调用）' },
    { type:'code', title:'用指针修改外部变量', content:'void swap(int* a, int* b) {\n    int t = *a;\n    *a = *b;\n    *b = t;\n}\n\nint x = 3, y = 5;\nswap(&x, &y);\ncout << x << " " << y << endl;  // 5 3（交换成功）' },
    { type:'sub', title:'函数指针' },
    { type:'para', content:'函数也有地址——函数名就是函数的入口地址。可以用指针指向一个函数，然后通过指针调用它。' },
    { type:'code', title:'函数指针', content:'int add(int a, int b) { return a + b; }\nint sub(int a, int b) { return a - b; }\n\n// 函数指针的声明：返回值类型 (*指针名)(参数列表)\nint (*calc)(int, int);\n\ncalc = add;\ncout << calc(10, 5) << endl;  // 15\n\ncalc = ⊂  // &可省略\ncout << calc(10, 5) << endl;  // 5' },

    { type:'section', title:'6️⃣ 引用（Reference）' },
    { type:'para', content:'引用就是一个变量的"别名"。引用和被引用的变量共享同一块内存地址。' },
    { type:'code', title:'引用的基本用法', content:'int x = 10;\nint& r = x;   // r是x的引用（别名）\n\ncout << x << " " << r << endl;  // 10 10\n\nr = 20;       // 通过引用修改x\ncout << x << endl;              // 20\n\n// x和r的地址完全相同\ncout << &x << " " << &r << endl; // 两个值一样' },
    { type:'sub', title:'引用作为函数参数' },
    { type:'code', title:'传引用实现交换', content:'void swap(int& a, int& b) {\n    int t = a;\n    a = b;\n    b = t;\n}\n\nint x = 3, y = 5;\nswap(x, y);    // 直接传变量，不用取地址\ncout << x << " " << y << endl;  // 5 3' },
    { type:'sub', title:'引用做函数返回值' },
    { type:'code', title:'返回引用支持链式赋值', content:'int arr[5] = {1,2,3,4,5};\n\nint& get(int idx) {\n    return arr[idx];\n}\n\nget(2) = 100;  // arr[2]变成100\ncout << arr[2] << endl;  // 100' },
    { type:'warning', content:'不要返回局部变量的引用！局部变量在函数返回后被销毁，引用变成悬空引用。 int& bad() { int x=10; return x; } ❌' },

    { type:'section', title:'7️⃣ 引用与指针的区别（高频考点）' },
    { type:'table', headers:['对比项','指针','引用'], rows:[
      ['初始化','可以不初始化（但危险）','必须初始化，且不能改变'],
      ['重新绑定','可以改指向其他对象','初始化后永远绑定同一个对象'],
      ['内存','占用内存（8字节/64位）','不额外占用（就是别名）'],
      ['空值','可为 nullptr','不能为空'],
      ['运算','支持加减、比较','不支持，引用就是原变量'],
      ['数组','有指针数组','没有引用的数组'],
      ['解引用','需要 *p 取内容','直接使用，如原变量'],
      ['多级','可以 int** pp','不能 int&& r（不是引用引用）'],
    ]},
    { type:'tip', content:'面试/笔试口诀：引用安全但死板——不能为空、不能改绑；指针灵活但危险——可以为空、可以加减。能用引用用引用，需要指针再用指针。' },

    { type:'section', title:'8️⃣ struct 结构体' },
    { type:'para', content:'结构体是一种用户自定义的复合数据类型，将多个不同类型的变量组合在一起。' },
    { type:'code', title:'定义与使用结构体', content:'struct Student {\n    string name;\n    int age;\n    double score;\n};   // ⚠️ 分号不能少！\n\nint main() {\n    Student s1;                        // 定义变量\n    s1.name = "张三";\n    s1.age  = 15;\n    s1.score = 98.5;\n    \n    Student s2 = {"李四", 16, 92.0};   // 聚合初始化\n    \n    cout << s1.name << " " << s1.score;\n    return 0;\n}' },
    { type:'sub', title:'结构体成员访问' },
    { type:'table', headers:['运算符','示例','含义'], rows:[
      ['.（点运算符）','s.name','通过变量名访问成员'],
      ['->（箭头运算符）','p->name','通过指针访问成员（等价于 (*p).name）'],
    ]},
    { type:'code', title:'结构体指针', content:'Student* p = &s1;\ncout << p->name;   // 等价于 (*p).name\ncout << (*p).age;' },
    { type:'sub', title:'结构体内存对齐（了解）' },
    { type:'para', content:'编译器不会把结构体的成员紧挨着存放，而是按一定规则对齐，以提升CPU的访问速度。' },
    { type:'code', title:'内存对齐示例', content:'struct A {\n    char c;    // 1字节\n    int  x;    // 4字节\n    char d;    // 1字节\n};  // sizeof(A) 可能是 12，不是6！\n\nstruct B {\n    int  x;    // 4字节\n    char c;    // 1字节\n    char d;    // 1字节\n};  // sizeof(B) 可能是 8' },
    { type:'tip', content:'把占用大的成员放在前面可以减少对齐浪费的空间。信奥赛不深究对齐细节，但要知道 sizeof(结构体) ≠ 成员字节数之和。' },
    { type:'sub', title:'结构体与函数' },
    { type:'para', content:'结构体作为参数默认是传值的（复制整个结构体），大数据量时推荐传引用或传指针。' },
    { type:'code', title:'结构体传参建议', content:'void print1(Student s) { }           // 传值——复制整个结构体，开销大\nvoid print2(const Student& s) { }     // 传引用——高效，不修改原数据\nvoid print3(const Student* p) { }     // 传指针——同样高效\n\n// 常用技巧：typedef 简化类型名\ntypedef struct { string name; int age; } Stu;\nStu s = {"王五", 17};' },

    { type:'section', title:'9️⃣ 结构体与指针的'联合'应用' },
    { type:'para', content:'在信奥赛中最常见的就是用结构体实现链表节点，或者用结构体+指针构建各种数据结构。' },
    { type:'code', title:'链表节点', content:'struct Node {\n    int data;\n    Node* next;   // 指向下一个节点\n    // 构造函数\n    Node(int d) : data(d), next(nullptr) {}\n};\n\nint main() {\n    Node* head = new Node(1);\n    head->next = new Node(2);\n    head->next->next = new Node(3);\n    \n    // 遍历链表\n    Node* cur = head;\n    while (cur != nullptr) {\n        cout << cur->data << " ";\n        cur = cur->next;\n    }\n    // 输出：1 2 3\n    return 0;\n}' },
    { type:'warning', content:'用 new 创建的对象要记得 delete！链表遍历完要把每个节点都释放，否则内存泄漏。' },

    { type:'section', title:'🔟 union 联合体' },
    { type:'para', content:'联合体（共用体）也是一种复合类型，但它所有的成员共享同一块内存空间。' },
    { type:'code', title:'联合体基础', content:'union Data {\n    int    i;    // 4字节\n    float  f;    // 4字节\n    char   c;    // 1字节\n};  // sizeof(Data) = 4（取最大成员的大小）\n\nData d;\nd.i = 65;\ncout << d.i << endl;  // 65\ncout << d.c << endl;  // 'A'（ASCII 65）——和i共享同一块内存！' },
    { type:'bullet', items:[
      '所有成员从同一地址开始，共用内存空间',
      'sizeof(union) = 最大成员的大小（考虑对齐）',
      '同一时刻只能使用一个成员——新值会覆盖旧值',
      '常用于节省内存或做类型转换（如解析网络协议）',
    ]},
    { type:'tip', content:'考试对比：struct 每个成员有自己的内存（大小 ≈ 成员之和+对齐），union 所有成员共用内存（大小 = 最大成员）。' },

    { type:'section', title:'📌 CSP-J/S 常考题型' },
    { type:'quiz', items:[
      { q:'int a=5; int* p=&a; *p=10; 之后 a 的值是？', options:['5','10','&a的地址','p的地址'], answer:1, explain:'p指向a，*p=10 通过解引用修改了a的值。' },
      { q:'64位系统上，char* 类型的指针占用多少个字节？', options:['1','4','8','取决于char数组的大小'], answer:2, explain:'所有类型指针在同一系统上大小相同，64位系统为8字节。' },
      { q:'以下代码输出什么？int arr[3]={1,2,3}; int* p=arr+1; cout<<p[1];', options:['1','2','3','随机值'], answer:2, explain:'p指向arr[1]，p[1]等价于*(p+1)=arr[2]=3。' },
      { q:'以下关于引用和指针的说法，错误的是？', options:['引用必须初始化，指针可以不初始化','指针可以改指向，引用不能改绑','可以有指针的指针，但不能有引用的引用','引用可以指向nullptr'], answer:3, explain:'引用不能为空，必须引用一个已存在的对象。' },
      { q:'struct 和 union 的关键区别是？', options:['struct 是C++的，union 是C的','struct所有成员共享内存，union各自独立','struct各自独立，union共享内存','union里不能放函数'], answer:2 },
    ]},
  ]
};
