// 模块07：C++语法基础
lessonsRaw['m7'] = {
  title: 'C++语法基础',
  icon: '📝',
  data: [
    { type:'objective', items:[
      '掌握C++的基本数据类型及其取值范围',
      '理解常量与变量的区别，学会变量命名规则',
      '熟悉运算符的优先级与结合性',
      '掌握 if/else、switch、for、while、do-while 等流程控制语句',
      '理解函数的定义、声明与调用',
      '区分全局作用域与局部作用域',
    ]},
    { type:'section', title:'1️⃣ 基本数据类型' },
    { type:'para', content:'C++ 是静态类型语言——每个变量必须先声明类型，才能在程序中使用。类型决定了变量占用的内存大小、能存储的数据范围以及可执行的操作。' },
    { type:'table', headers:['类型','关键字','占用字节','取值范围'], rows:[
      ['整型（短）','short','2','-32,768 ~ 32,767'],
      ['整型','int','4','-2,147,483,648 ~ 2,147,483,647'],
      ['整型（长）','long long','8','-9.22×10¹⁸ ~ 9.22×10¹⁸'],
      ['无符号整型','unsigned int','4','0 ~ 4,294,967,295'],
      ['单精度浮点','float','4','约 ±3.4×10⁻³⁸ ~ ±3.4×10³⁸，精度7位'],
      ['双精度浮点','double','8','约 ±1.7×10⁻³⁰⁸ ~ ±1.7×10³⁰⁸，精度15位'],
      ['字符','char','1','-128 ~ 127 或 0~255（ASCII码）'],
      ['布尔','bool','1','true / false'],
    ]},
    { type:'warning', content:'信奥赛必坑：int 范围约 ±21亿。如果数值可能超过这个范围（例如 10⁹ × 10⁹ = 10¹⁸），一定要用 long long！否则会溢出导致答案错误。' },
    { type:'code', title:'数据类型示例', content:'int a = 2147483647;          // OK, int 最大值\nlong long b = 1000000000000LL; // 大数加 LL 后缀\nfloat f = 3.14f;               // float 加 f 后缀\ndouble d = 3.14159265358979;   // double 精度更高\nchar c = \'A\';                  // 字符用单引号\nbool flag = true;               // true / false' },

    { type:'section', title:'2️⃣ 常量与变量' },
    { type:'sub', title:'变量（Variable）' },
    { type:'para', content:'变量是内存中一个有名字的存储单元，其值在程序运行中可以改变。声明规则：类型 + 变量名（标识符）。' },
    { type:'bullet', items:[
      '标识符由字母、数字、下划线组成，不能以数字开头',
      '不能使用C++保留关键字（int、if、while 等）',
      '区分大小写：sum、Sum、SUM 是三个不同的变量',
      '建议使用有意义的名称（驼峰命名或下划线命名），如 studentScore 或 student_score',
    ]},
    { type:'sub', title:'常量（Constant）' },
    { type:'para', content:'常量是值不可变的量。C++ 中可以用 const 或 #define 定义常量。' },
    { type:'code', title:'常量的两种定义方式', content:'// 方式1：const 关键字（推荐，有类型检查）\nconst double PI = 3.1415926;\nconst int MAX_N = 100005;\n\n// 方式2：宏定义（预处理阶段替换，⚠️ 无类型检查）\n#define PI 3.1415926\n#define MAX_N 100005\n\nint main() {\n    // PI = 3.14;  ❌ 错误！常量不可修改\n    return 0;\n}' },
    { type:'tip', content:'const 优于 #define：const 有数据类型和作用域，编译器可以做类型检查；#define 只是文本替换，容易引发错误（如 #define MAX 100+10 写 MAX*2 会变成 100+10*2 = 120 而非 220）。' },

    { type:'section', title:'3️⃣ 运算符与优先级' },
    { type:'para', content:'C++ 有丰富的运算符。优先级决定表达式中哪个运算先执行，结合性决定同级运算符的执行顺序。' },
    { type:'table', headers:['优先级','运算符','含义','结合性'], rows:[
      ['1（最高）','() :: . -> []','作用域、下标、函数调用','左→右'],
      ['2','++  --  !  ~  +  -  *  &  (type)','单目运算符（自增、取反、取地址、强制转换）','右→左'],
      ['3','*  /  %','乘法、除法、取模','左→右'],
      ['4','+  -','加法、减法','左→右'],
      ['5','<<  >>','左移、右移（位运算）','左→右'],
      ['6','<  <=  >  >=','关系比较','左→右'],
      ['7','==  !=','等于、不等于','左→右'],
      ['8','&','按位与','左→右'],
      ['9','^','按位异或','左→右'],
      ['10','|','按位或','左→右'],
      ['11','&&','逻辑与','左→右'],
      ['12','||','逻辑或','左→右'],
      ['13（最低）','=  +=  -=  *=  /=  %=','赋值及复合赋值','右→左'],
    ]},
    { type:'warning', content:'易错点：1）== 和 = 混淆——if (x = 5) 会把 5 赋给 x，条件永远为真！2）&& 优先级高于 ||，所以 a || b && c 等价于 a || (b && c)。3）位运算优先级比比较运算符低！' },
    { type:'code', title:'运算符优先级陷阱', content:'int a = 1, b = 2, c = 3;\nint x = a + b * c;       // 1 + (2*3) = 7\nint y = a << b + c;       // 1 << (2+3) = 32  ⚠️ + 优先级高于 <<\nbool z = a & b == 0;      // a & (b==0) = 1 & 0 = 0  ⚠️ == 优先级高于 &\n                           // 实际意图很可能是 (a & b) == 0 → 1' },
    { type:'tip', content:'当你不确定优先级时，加括号！代码是给人读的，可读性比"炫技"更重要。' },

    { type:'section', title:'4️⃣ 流程控制' },
    { type:'sub', title:'if / else if / else' },
    { type:'para', content:'条件分支语句，根据条件表达式的真假选择执行路径。' },
    { type:'code', title:'if-else 结构', content:'int score;\ncin >> score;\n\nif (score >= 90) {\n    cout << "优秀" << endl;\n} else if (score >= 60) {\n    cout << "及格" << endl;\n} else {\n    cout << "不及格" << endl;\n}\n\n// 简洁写法（但注意不要混淆 = 和 ==）\nint maxVal = (a > b) ? a : b;  // 三目运算符' },
    { type:'warning', content:'if / else if 链中，条件按顺序判断。一旦某个条件为真，后面的 else if 和 else 都不会执行。因此"范围型"条件要从小到大或从大到小排列。' },

    { type:'sub', title:'switch 语句' },
    { type:'para', content:'switch 用于多路分支，判断条件必须是整型或枚举类型。每个 case 后必须有 break，否则会"穿透"（fall-through）到下一个 case。' },
    { type:'code', title:'switch 示例', content:'int day;\ncin >> day;\n\nswitch (day) {\n    case 1:\n        cout << "周一" << endl;\n        break;\n    case 2:\n        cout << "周二" << endl;\n        break;\n    case 3:\n    case 4:\n    case 5:\n        cout << "工作日" << endl;  // 穿透：3,4,5 都执行这里\n        break;\n    default:\n        cout << "周末！" << endl;\n}' },

    { type:'sub', title:'for 循环' },
    { type:'para', content:'for 循环将初始化、条件判断、循环变量更新集中在一个语句中，适用于已知循环次数的情况。' },
    { type:'code', title:'for 循环', content:'// 语法：for (初始化; 条件; 更新) { 循环体 }\nfor (int i = 1; i <= 10; i++) {\n    cout << i << " ";        // 输出 1 到 10\n}\n\n// 循环嵌套：打印九九乘法表\nfor (int i = 1; i <= 9; i++) {\n    for (int j = 1; j <= i; j++) {\n        cout << j << "×" << i << "=" << i*j << "\\t";\n    }\n    cout << endl;\n}' },

    { type:'sub', title:'while 和 do-while 循环' },
    { type:'para', content:'while 先判断条件再执行（可能一次都不执行），do-while 先执行一次再判断（至少执行一次）。' },
    { type:'code', title:'while 与 do-while', content:'// while — 先判断\nint n = 12345;\nwhile (n > 0) {\n    cout << n % 10;  // 逆序输出每一位\n    n /= 10;\n}\n\n// do-while — 至少执行一次\nint x;\ndo {\n    cout << "请输入一个正数：";\n    cin >> x;\n} while (x <= 0);' },
    { type:'tip', content:'for 适合"知道循环次数"的场景，while 适合"不知道次数但知道结束条件"的场景。信奥赛读文件输入（如 while (cin >> x)）是最常用的循环模式。' },

    { type:'section', title:'5️⃣ 函数定义与调用' },
    { type:'para', content:'函数是一段可重复调用的代码块。C++ 程序的执行从 main 函数开始。使用函数可以避免代码重复，提高可读性和可维护性。' },
    { type:'bullet', items:[
      '函数四要素：返回类型、函数名、参数列表（可能为空）、函数体',
      '函数声明（函数原型）：告诉编译器函数的存在，可以放在调用之前',
      '函数定义：包含函数体的完整实现',
      '如果函数定义在 main 之后，需要在 main 之前声明（否则编译错误）',
    ]},
    { type:'code', title:'函数声明与定义', content:'#include <iostream>\nusing namespace std;\n\n// 函数声明（原型）——写在 main 之前\nint add(int a, int b);   // 返回两个整数之和\nbool isPrime(int n);     // 判断素数\n\nint main() {\n    int sum = add(3, 5);        // 调用 add 函数\n    cout << sum << endl;         // 输出 8\n    \n    if (isPrime(17)) {\n        cout << "17 是素数" << endl;\n    }\n    return 0;\n}\n\n// 函数定义——写在 main 之后\nint add(int a, int b) {\n    return a + b;\n}\n\nbool isPrime(int n) {\n    if (n < 2) return false;\n    for (int i = 2; i * i <= n; i++) {\n        if (n % i == 0) return false;\n    }\n    return true;\n}' },
    { type:'warning', content:'函数必须有"返回类型"。如果不需要返回值，使用 void 类型。不要忘记写返回值！在 main 函数中，return 0 表示程序正常结束（可以省略，编译器会自动添加）。' },

    { type:'section', title:'6️⃣ 作用域（全局 vs 局部）' },
    { type:'para', content:'作用域决定了变量在程序中的可见范围。C++ 中最基本的作用域规则：大括号 { } 内定义的变量只在内部可见。' },
    { type:'table', headers:['作用域','定义位置','特点','示例'], rows:[
      ['全局作用域','所有函数之外','整个文件可见，程序启动时创建，结束时销毁','int globalVar = 10;'],
      ['局部作用域','函数或块内','只在 {} 内部可见，块结束时销毁', 'int x = 5; // 在 main 里'],
      ['函数参数作用域','函数参数列表','仅在函数体内部可见','int add(int a, int b)'],
      ['命名空间作用域','namespace 内','通过 using 或 命名空间:: 访问','std::cout'],
    ]},
    { type:'code', title:'作用域示例', content:'#include <iostream>\nusing namespace std;\n\nint global = 100;   // 全局变量 — 任何地方都可以访问\n\nvoid func() {\n    int local = 10;  // 局部变量 — 仅在 func() 内部可见\n    cout << "global in func: " << global << endl;  // 100\n    cout << "local: " << local << endl;             // 10\n}\n\nint main() {\n    cout << global << endl;  // 100 — 全局变量可以直接访问\n    // cout << local;        // ❌ 错误！local 不在这个作用域\n    \n    int global = 200;       // ⚠️ 同名局部变量会"遮蔽"全局变量\n    cout << global << endl;  // 200（局部优先）\n    cout << ::global << endl;// 100（使用全局作用域运算符 ::）\n    return 0;\n}' },
    { type:'warning', content:'尽量避免过多使用全局变量！全局变量容易被意外修改，导致程序难以调试。竞賽中通常只在需要时定义全局常量和数组（如 int a[100005]; 通常放全局）。' },
    { type:'tip', content:'C++ 使用"就近原则"——当局部变量和全局变量同名时，在当前作用域中局部变量优先。使用作用域解析运算符 :: 可以强制访问全局变量。' },

    { type:'section', title:'📌 CSP-J/S 常考题型' },
    { type:'quiz', items:[
      { q:'以下哪个数据类型最适合存储 10¹² 的数值？', options:['int','long long','float','double'], answer:1, explain:'int 最大约 21亿（2.1×10⁹），10¹² 远超此范围，必须用 long long。' },
      { q:'表达式 3 + 5 * 2 - 8 / 4 的结果是？', options:['5','8','11','14'], answer:2, explain:'3 + (5*2) - (8/4) = 3 + 10 - 2 = 11。' },
      { q:'以下关于 switch 语句的说法，正确的是？', options:['case 后面必须用大括号','每个 case 必须有 break，否则会穿透','switch 条件可以是 float 类型','default 必须放在最后'], answer:1 },
      { q:'以下关于作用域的说法，错误的是？', options:['全局变量在所有函数外定义','局部变量只在定义它的块内可见','同名局部变量会遮蔽全局变量','全局变量比局部变量更安全，应该多用'], answer:3, explain:'全局变量容易被意外修改，应尽量少用，只在必要时使用。' },
      { q:'以下哪项是 C++ 合法的变量名？', options:['2ndPlace','int','my-var','_count'], answer:3, explain:'不能以数字开头（❌2ndPlace），不能用关键字（❌int），不能含连字符（❌my-var），下划线开头是合法的（✅_count）。' },
    ]},
  ]
};
