// 模块11：STL标准库
lessonsRaw['m11'] = {
  title: 'STL标准库',
  icon: '📚',
  data: [
    { type:'objective', items:[
      '掌握 STL 六大组件的概念',
      '熟练使用 vector 动态数组',
      '掌握 stack、queue、priority_queue 容器适配器',
      '会用 map 和 set 管理键值对与集合',
      '掌握 algorithm 中常用的函数',
    ]},

    { type:'section', title:'1️⃣ STL 概述' },
    { type:'para', content:'STL（Standard Template Library，标准模板库）是C++标准库的核心组成部分。它提供了通用的数据结构和算法，让你不用自己造轮子。' },
    { type:'bullet', items:[
      '容器（Containers）：存储数据的结构（vector, map, set, list 等）',
      '迭代器（Iterators）：遍历容器元素的工具（类似指针）',
      '算法（Algorithms）：对容器进行操作的函数（sort, find, reverse 等）',
      '适配器（Adapters）：对容器进行包装（stack, queue, priority_queue）',
      '仿函数（Functors）：重载了 operator() 的类',
      '分配器（Allocators）：管理内存分配（日常很少用）',
    ]},
    { type:'tip', content:'信奥赛不需要全部掌握，但 vector, stack, queue, priority_queue, map, set, sort, lower_bound 是必须熟练的。' },

    { type:'section', title:'2️⃣ vector——动态数组' },
    { type:'para', content:'vector 是一个可以自动扩容的"动态数组"。它在连续内存中存储元素，支持随机访问（O(1)），尾部插入/删除摊销 O(1)。' },
    { type:'sub', title:'引入与声明' },
    { type:'code', title:'包含头文件与声明', content:'#include <vector>\nusing namespace std;\n\nvector<int> v1;              // 空的vector\nvector<int> v2(10);          // 10个元素，默认初始化为0\nvector<int> v3(10, 5);       // 10个元素，全部为5\nvector<int> v4 = {1,2,3,4};  // 初始化列表（C++11）\nvector<int> v5(v4);          // 复制构造\nvector<vector<int>> mat(3, vector<int>(4, 0)); // 二维数组，3行4列全为0' },
    { type:'sub', title:'常用方法' },
    { type:'table', headers:['方法','功能','时间复杂度'], rows:[
      ['push_back(x)','尾部添加元素 x','O(1) 摊销'],
      ['pop_back()','删除尾部元素','O(1)'],
      ['size()','返回元素个数','O(1)'],
      ['empty()','判断是否为空','O(1)'],
      ['clear()','清空所有元素','O(n)'],
      ['at(i)','访问下标 i（带越界检查）','O(1)'],
      ['front() / back()','访问第一个/最后一个元素','O(1)'],
      ['begin() / end()','返回首/尾迭代器','O(1)'],
      ['insert(pos, x)','在 pos 位置插入 x','O(n)'],
      ['erase(pos)','删除 pos 位置的元素','O(n)'],
      ['resize(n)','重新设置大小为 n','O(n)'],
      ['reserve(n)','预分配 n 个元素的空间','O(n)'],
    ]},
    { type:'code', title:'vector 基本操作', content:'vector<int> v = {3, 1, 4, 1, 5};\n\nv.push_back(9);              // {3,1,4,1,5,9}\ncout << v.size() << endl;    // 6\n\n// 随机访问\ncout << v[2] << endl;        // 4（不检查越界）\ncout << v.at(2) << endl;     // 4（越界抛异常）\n\n// 遍历方式1：下标\nfor (int i = 0; i < v.size(); i++)\n    cout << v[i] << " ";\n\n// 遍历方式2：范围for（推荐）\nfor (int x : v)\n    cout << x << " ";\n\n// 遍历方式3：迭代器\nfor (auto it = v.begin(); it != v.end(); it++)\n    cout << *it << " ";' },
    { type:'warning', content:'at() 比 [] 安全——越界访问时会抛 out_of_range 异常。但 [] 更快（不检查下标）。信奥赛中为了效率常用 []，调试阶段推荐 at()。' },
    { type:'sub', title:'二维 vector' },
    { type:'code', title:'二维数组与不定长行', content:'// 固定行列\nvector<vector<int>> mat(3, vector<int>(4, 0));\n\n// 不定长（每行长度不同）\nvector<vector<int>> triangle;\nfor (int i = 1; i <= 5; i++) {\n    triangle.push_back(vector<int>(i, 1));\n}\n/* 杨辉三角\n1\n1 1\n1 1 1\n1 1 1 1\n1 1 1 1 1\n*/' },

    { type:'section', title:'3️⃣ stack——栈' },
    { type:'para', content:'stack 是一种"后进先出"（LIFO）的数据结构。它是容器适配器——底层默认用 deque 实现。' },
    { type:'code', title:'stack 用法', content:'#include <stack>\nstack<int> st;\n\nst.push(10);    // 入栈\nst.push(20);\nst.push(30);\n\ncout << st.top() << endl;  // 30——栈顶元素\nst.pop();                  // 弹出栈顶\ncout << st.top() << endl;  // 20\ncout << st.size() << endl; // 2\ncout << st.empty() << endl;// 0（false）' },
    { type:'table', headers:['方法','功能','复杂度'], rows:[
      ['push(x)','元素 x 入栈','O(1)'],
      ['pop()','弹出栈顶元素','O(1)'],
      ['top()','返回栈顶元素引用','O(1)'],
      ['size()','栈中元素个数','O(1)'],
      ['empty()','是否为空','O(1)'],
    ]},
    { type:'tip', content:'stack 没有迭代器，不能遍历——只能访问栈顶元素。如果要遍历请用 vector 或 deque。' },

    { type:'section', title:'4️⃣ queue——队列' },
    { type:'para', content:'queue 是"先进先出"（FIFO）的数据结构。也是容器适配器，底层默认用 deque。' },
    { type:'code', title:'queue 用法', content:'#include <queue>\nqueue<int> q;\n\nq.push(10);    // 入队（尾）\nq.push(20);\nq.push(30);\n\ncout << q.front() << endl; // 10——队首\ncout << q.back()  << endl; // 30——队尾\n\nq.pop();                   // 弹出队首\ncout << q.front() << endl; // 20' },
    { type:'table', headers:['方法','功能','复杂度'], rows:[
      ['push(x)','元素 x 入队','O(1)'],
      ['pop()','弹出队首元素','O(1)'],
      ['front()','队首元素引用','O(1)'],
      ['back()','队尾元素引用','O(1)'],
      ['size() / empty()','大小/判空','O(1)'],
    ]},

    { type:'section', title:'5️⃣ priority_queue——优先队列（堆）' },
    { type:'para', content:'priority_queue 默认是"大根堆"——每次取出的都是最大的元素。底层用 vector 实现堆结构。' },
    { type:'code', title:'默认大根堆', content:'#include <queue>\npriority_queue<int> pq;\n\npq.push(5);\npq.push(1);\npq.push(9);\npq.push(3);\n\ncout << pq.top() << endl;  // 9——最大元素\npq.pop();                  // 弹出9\ncout << pq.top() << endl;  // 5' },
    { type:'sub', title:'小根堆的两种写法' },
    { type:'code', title:'小根堆', content:'// 方法1：用 greater\npriority_queue<int, vector<int>, greater<int>> pq1;\n\n// 方法2：插入负值（取巧）\npriority_queue<int> pq2;\npq2.push(-5); pq2.push(-1); pq2.push(-9);\ncout << -pq2.top() << endl;  // 1（原本的最小值）' },
    { type:'table', headers:['方法','功能','复杂度'], rows:[
      ['push(x)','插入元素','O(log n)'],
      ['pop()','弹出堆顶','O(log n)'],
      ['top()','返回堆顶（最大/最小）','O(1)'],
      ['size() / empty()','大小/判空','O(1)'],
    ]},
    { type:'tip', content:'priority_queue 只有 top() 没有 front() 和 back()。内部使用堆排序维护，插入和删除都是 O(log n)。排序操作可考虑用 make_heap 等。' },

    { type:'section', title:'6️⃣ map——映射/字典' },
    { type:'para', content:'map 存储键值对（key-value pair）。key 唯一且自动按 key 排序（底层是红黑树）。' },
    { type:'code', title:'map 的基本操作', content:'#include <map>\nmap<string, int> mp;\n\n// 插入\nmp["Alice"] = 95;          // 方式1：[]运算符\nmp.insert({"Bob", 87});    // 方式2：insert\nmp["Charlie"] = 92;\n\n// 访问\ncout << mp["Alice"] << endl;  // 95\n\n//   []访问不存在的key会自动插入，默认值0\ncout << mp["David"] << endl;  // 0（David被自动插入）\n\n// 查找（推荐用find，不会插入新元素）\nauto it = mp.find("Bob");\nif (it != mp.end()) {\n    cout << it->first << " : " << it->second << endl;\n    // 输出 Bob : 87\n}\n\n// 遍历\nfor (auto& p : mp) {\n    cout << p.first << " : " << p.second << endl;\n}' },
    { type:'table', headers:['方法','功能','复杂度'], rows:[
      ['[key]','访问/插入 key，不存在则创建默认值','O(log n)'],
      ['at(key)','安全访问（抛异常），不会自动插入','O(log n)'],
      ['insert({k,v})','插入键值对','O(log n)'],
      ['find(key)','查找 key，返回迭代器','O(log n)'],
      ['count(key)','key是否存在（0或1）','O(log n)'],
      ['erase(key)','删除指定key','O(log n)'],
      ['size()','键值对数量','O(1)'],
    ]},
    { type:'warning', content:'mp[key] 如果 key 不存在会自动插入一个默认值（int为0，string为""）。如果你只是想知道 key 是否存在，用 find() 或 count() 而不是 []！' },
    { type:'sub', title:'unordered_map（哈希表）' },
    { type:'para', content:'C++11 提供了 unordered_map，底层用哈希表实现，查找 O(1) 平均，但元素无序。适合只关心查找、不关心顺序的场景。' },
    { type:'code', title:'unordered_map', content:'#include <unordered_map>\nunordered_map<string, int> ump;\nump["Alice"] = 95;\nump["Bob"] = 87;\n// 用法和map一样，只是内部无序，访问速度更快（O(1)平均）' },
    { type:'table', headers:['对比','map','unordered_map'], rows:[
      ['底层结构','红黑树','哈希表'],
      ['查找复杂度','O(log n)','O(1) 平均 / O(n) 最坏'],
      ['有序性','自动升序排列','无序'],
      ['适用场景','需要有序遍历','追求速度，不关心顺序'],
    ]},

    { type:'section', title:'7️⃣ set——集合' },
    { type:'para', content:'set 存储不重复的元素，自动按升序排列（也是红黑树实现）。' },
    { type:'code', title:'set 用法', content:'#include <set>\nset<int> st;\n\nst.insert(5);\nst.insert(1);\nst.insert(9);\nst.insert(3);\nst.insert(3);  // 重复插入被忽略\n\n// 自动升序\nfor (int x : st)\n    cout << x << " ";  // 1 3 5 9\n\nauto it = st.find(5);\nif (it != st.end())\n    cout << "找到了" << endl;\n\nst.erase(3);  // 删除元素3\ncout << st.count(3) << endl;  // 0（已删除）' },
    { type:'table', headers:['方法','功能','复杂度'], rows:[
      ['insert(x)','插入元素','O(log n)'],
      ['find(x)','查找元素，返回迭代器','O(log n)'],
      ['count(x)','元素出现次数（set中只能是0或1）','O(log n)'],
      ['erase(x)','删除元素','O(log n)'],
      ['lower_bound(x)','≥x的最小元素','O(log n)'],
      ['upper_bound(x)','>x的最小元素','O(log n)'],
    ]},
    { type:'tip', content:'set 和 map 的区别：set 只存 key（值本身），map 存 key-value。set 的迭代器不能修改元素（因为是常量）。' },
    { type:'sub', title:'multiset 和 unordered_set' },
    { type:'bullet', items:[
      'multiset：允许重复元素的 set，count() 可能 > 1',
      'unordered_set：哈希实现，元素无序，查找 O(1) 平均',
      'unordered_multiset：同时允许重复且无序',
    ]},

    { type:'section', title:'8️⃣ algorithm 常用函数' },
    { type:'para', content:'<algorithm> 提供了大量通用算法，配合迭代器使用。' },
    { type:'sub', title:'sort——排序' },
    { type:'code', title:'sort 用法', content:'#include <algorithm>\n\nvector<int> v = {5, 2, 8, 1, 9};\n\n// 升序排序（默认）\nsort(v.begin(), v.end());\n// v = {1, 2, 5, 8, 9}\n\n// 降序排序\nsort(v.begin(), v.end(), greater<int>());\n// v = {9, 8, 5, 2, 1}\n\n// 自定义排序规则\nsort(v.begin(), v.end(), [](int a, int b) {\n    return a > b;  // 降序\n});\n\n// 部分排序：只排前3个\npartial_sort(v.begin(), v.begin()+3, v.end());' },
    { type:'warning', content:'sort 必须支持随机访问迭代器（vector, deque, array, 原生数组）。list 不行，list 用 sort() 成员函数。sort 平均 O(n log n)。' },
    
    { type:'sub', title:'reverse——反转' },
    { type:'code', title:'reverse', content:'vector<int> v = {1, 2, 3, 4, 5};\nreverse(v.begin(), v.end());\n// v = {5, 4, 3, 2, 1}\n\nstring s = "hello";\nreverse(s.begin(), s.end());\n// s = "olleh"' },
    
    { type:'sub', title:'min / max —— 最值' },
    { type:'code', title:'min / max', content:'int a = 3, b = 5;\ncout << min(a, b) << endl;  // 3\ncout << max(a, b) << endl;  // 5\n\n// minmax：同时返回最小和最大\nauto p = minmax({3, 1, 4, 1, 5});\ncout << p.first << " " << p.second;  // 1 5\n\n// min_element / max_element：返回迭代器\nvector<int> v = {3, 1, 4, 1, 5};\nauto it = min_element(v.begin(), v.end());\ncout << *it << endl;  // 1（最小值）' },
    
    { type:'sub', title:'lower_bound / upper_bound——二分查找' },
    { type:'para', content:'lower_bound 和 upper_bound 要求数组是已排序的（升序）。它们使用二分查找，效率 O(log n)。' },
    { type:'code', title:'lower_bound / upper_bound', content:'vector<int> v = {1, 2, 2, 2, 3, 4, 5};\n\n// lower_bound：第一个 ≥ x 的元素位置\nauto it1 = lower_bound(v.begin(), v.end(), 2);\ncout << it1 - v.begin() << endl;  // 1（v[1]=2）\n\n// upper_bound：第一个 > x 的元素位置\nauto it2 = upper_bound(v.begin(), v.end(), 2);\ncout << it2 - v.begin() << endl;  // 4（v[4]=3）\n\n// 元素2出现的范围：[lower, upper)\nint cnt = it2 - it1;\ncout << cnt << endl;  // 3（三个2）' },
    { type:'tip', content:'lower_bound 的"大于等于"和 upper_bound 的"大于"要分清。统计元素 x 的出现次数 = upper_bound - lower_bound。二分查找的前提是数组必须有序！' },

    { type:'sub', title:'其他常用算法' },
    { type:'code', title:'unique——去重（相邻）', content:'vector<int> v = {1, 1, 2, 2, 2, 3, 4, 4, 5};\n\n// unique 把不重复元素移到前面，返回新逻辑结尾\nauto last = unique(v.begin(), v.end());\n// v = {1, 2, 3, 4, 5, ?, ?, ?, ?}\n// 后面的元素理论上被移走了\nv.erase(last, v.end());  // 删掉多余的\n// v = {1, 2, 3, 4, 5}\n\n// 先排序再去重，得到所有不重复元素\nsort(v.begin(), v.end());\nv.erase(unique(v.begin(), v.end()), v.end());' },
    { type:'code', title:'其他有用函数', content:'// fill——填充\nvector<int> v(5);\nfill(v.begin(), v.end(), 10);\n// v = {10, 10, 10, 10, 10}\n\n// count——计数\nvector<int> v2 = {1, 2, 2, 2, 3};\ncout << count(v2.begin(), v2.end(), 2);  // 3\n\n// find——线性查找\nvector<int> v3 = {3, 1, 4, 1, 5};\nauto it = find(v3.begin(), v3.end(), 4);\nif (it != v3.end())\n    cout << *it << " at " << (it - v3.begin());  // 4 at 2\n\n// next_permutation——下一个排列\nvector<int> p = {1, 2, 3};\ndo {\n    for (int x : p) cout << x << " ";\n    cout << endl;\n} while (next_permutation(p.begin(), p.end()));\n// 输出 1 2 3, 1 3 2, 2 1 3, 2 3 1, 3 1 2, 3 2 1' },

    { type:'section', title:'9️⃣ 容器对比总结' },
    { type:'table', headers:['容器','底层','有序','重复','查找','增删'], rows:[
      ['vector','动态数组','下标序','允许','O(n)','尾部O(1)'],
      ['deque','双端队列','下标序','允许','O(n)','两端O(1)'],
      ['list','双向链表','无','允许','O(n)','O(1)已知位置'],
      ['set','红黑树','升序','否','O(log n)','O(log n)'],
      ['multiset','红黑树','升序','是','O(log n)','O(log n)'],
      ['map','红黑树','按key','key唯一','O(log n)','O(log n)'],
      ['unordered_set','哈希表','否','否','O(1)平均','O(1)平均'],
      ['stack','适配器','LIFO','-','-','top O(1)'],
      ['queue','适配器','FIFO','-','-','front O(1)'],
      ['priority_queue','堆','按优先级','-','-','push/pop O(log n)'],
    ]},

    { type:'section', title:'📌 CSP-J/S 常考题型' },
    { type:'quiz', items:[
      { q:'vector 尾部插入一个元素的时间复杂度是？', options:['O(1)','O(log n)','O(n)','O(n log n)'], answer:0, explain:'push_back 摊还分析为 O(1)。' },
      { q:'以下哪个容器适合"先进先出"的数据访问？', options:['stack','queue','priority_queue','set'], answer:1 },
      { q:'priority_queue 默认是什么结构？', options:['小根堆','大根堆','队列','红黑树'], answer:1 },
      { q:'lower_bound(v.begin(), v.end(), x) 返回的是？', options:['第一个大于x的元素','第一个大于等于x的元素','第一个等于x的元素','最后一个等于x的元素'], answer:1 },
      { q:'以下关于 map 的说法错误的是？', options:['用[]访问不存在的key会自动插入','map底层是红黑树','map的key不允许重复','map 的元素无序'], answer:3, explain:'map 的元素按 key 自动升序排列。' },
      { q:'以下代码输出什么？vector<int> v={1,2,2,2,3}; auto l=lower_bound(v.begin(),v.end(),2); auto u=upper_bound(v.begin(),v.end(),2); cout<<u-l;', options:['1','2','3','4'], answer:2, explain:'2出现了3次，v[1],v[2],v[3]都是2。' },
    ]},
  ]
};
