// 模块12：基本数据结构
lessonsRaw['m12'] = {
  title: '基本数据结构',
  icon: '🏗️',
  data: [
    { type:'objective', items:[
      '理解栈（后进先出）和队列（先进先出）的原理，能手写实现',
      '掌握单向/双向/循环链表的结构和基本操作',
      '理解二叉树的四种遍历方式',
      '掌握完全二叉树的编号规律',
      '理解堆（大根堆/小根堆）的结构和操作',
      '掌握图的两种存储方式和两种遍历方法',
    ]},

    { type:'section', title:'1️⃣ 数据结构概述' },
    { type:'para', content:'数据结构是计算机中组织和存储数据的方式。选择合适的数据结构能让算法效率大大提高。' },
    { type:'table', headers:['数据结构','特点','典型应用'], rows:[
      ['栈','后进先出（LIFO）','函数调用、括号匹配、撤销操作'],
      ['队列','先进先出（FIFO）','排队系统、BFS、任务调度'],
      ['链表','动态分配、灵活插入/删除','内存管理、LRU缓存'],
      ['树','层次结构、分治','文件系统、数据库索引、表达式树'],
      ['堆','完全二叉树 + 堆序性','优先队列、Dijkstra、堆排序'],
      ['图','节点+边、网状关系','社交网络、最短路径、地图导航'],
    ]},

    { type:'section', title:'2️⃣ 栈（Stack）——后进先出' },
    { type:'para', content:'栈是一种"后进先出"（Last In First Out，LIFO）的线性表。只能在栈顶进行插入（入栈/push）和删除（出栈/pop）操作。' },
    { type:'sub', title:'手动实现栈' },
    { type:'code', title:'用数组实现栈', content:'const int MAXN = 100005;\nint stk[MAXN];\nint top = -1;   // 栈顶指针，-1表示空栈\n\n// 入栈\nvoid push(int x) {\n    stk[++top] = x;\n}\n\n// 出栈\nvoid pop() {\n    if (top >= 0) top--;\n}\n\n// 取栈顶\nint topElement() {\n    return stk[top];\n}\n\n// 判空\nbool empty() {\n    return top == -1;\n}\n\n// 大小\nint size() {\n    return top + 1;\n}\n\n// 使用\npush(10); push(20); push(30);\ncout << topElement() << endl;   // 30\npop();\ncout << topElement() << endl;   // 20\ncout << size() << endl;         // 2' },
    { type:'tip', content:'top初始化为 -1 表示空栈。top 的值就是当前栈顶的索引。入栈时先 ++top 再赋值，出栈时直接 top--（逻辑删除，数据还在但被视为无效）。' },
    { type:'sub', title:'栈的应用——括号匹配' },
    { type:'code', title:'判断括号是否匹配', content:'bool isMatching(string s) {\n    stack<char> st;\n    for (char c : s) {\n        if (c == '(' || c == '[' || c == '{') {\n            st.push(c);\n        } else {\n            if (st.empty()) return false;\n            char top = st.top();\n            if ((c == ')' && top != '(') ||\n                (c == ']' && top != '[') ||\n                (c == '}' && top != '{'))\n                return false;\n            st.pop();\n        }\n    }\n    return st.empty();\n}\n\ncout << isMatching("({[]})");   // 1 (true)\ncout << isMatching("({[})");    // 0 (false)' },

    { type:'section', title:'3️⃣ 队列（Queue）——先进先出' },
    { type:'para', content:'队列是一种"先进先出"（First In First Out，FIFO）的线性表。只能在队尾插入（入队），队首删除（出队）。' },
    { type:'sub', title:'手动实现循环队列' },
    { type:'code', title:'用数组实现循环队列', content:'const int MAXN = 100005;\nint q[MAXN];\nint front = 0, rear = 0;  // 队列为空时 front == rear\n\n// 入队\nvoid push(int x) {\n    q[rear] = x;\n    rear = (rear + 1) % MAXN;  // 循环\n}\n\n// 出队\nvoid pop() {\n    if (front != rear)\n        front = (front + 1) % MAXN;\n}\n\n// 队首\nint frontElement() {\n    return q[front];\n}\n\n// 判空\nbool empty() {\n    return front == rear;\n}\n\n// 大小\nint size() {\n    return (rear - front + MAXN) % MAXN;\n}\n\n// 使用\npush(10); push(20); push(30);\ncout << frontElement() << endl;  // 10\npop();\ncout << frontElement() << endl;  // 20' },
    { type:'warning', content:'循环队列用取模实现"循环"效果，rear 和 front 会在数组里绕圈。注意区分"队空"（front==rear）和"队满"（(rear+1)%N==front）。通常浪费一个元素空间来区分。' },

    { type:'section', title:'4️⃣ 链表（Linked List）' },
    { type:'para', content:'链表由一系列节点组成，每个节点包含数据域和指针域（指向下一个/前一个节点）。链表可以动态增长/缩小，插入/删除操作不需要移动大量元素。' },
    
    { type:'sub', title:'单向链表（Singly Linked List）' },
    { type:'code', title:'单向链表定义与基本操作', content:'struct Node {\n    int data;\n    Node* next;\n    Node(int d) : data(d), next(nullptr) {}\n};\n\n// 创建链表：1->2->3\nNode* head = new Node(1);\nhead->next = new Node(2);\nhead->next->next = new Node(3);\n\n// 遍历\nNode* cur = head;\nwhile (cur != nullptr) {\n    cout << cur->data << " ";\n    cur = cur->next;\n}\n// 输出：1 2 3\n\n// 在头部插入0\nNode* newNode = new Node(0);\nnewNode->next = head;\nhead = newNode;\n// 0->1->2->3\n\n// 删除值为2的节点\ncur = head;\nwhile (cur->next != nullptr && cur->next->data != 2)\n    cur = cur->next;\nif (cur->next != nullptr) {\n    Node* tmp = cur->next;\n    cur->next = cur->next->next;\n    delete tmp;\n}\n// 0->1->3' },
    { type:'tip', content:'链表插入/删除操作的关键是"改指针指向，别让节点丢失"。先连接新节点，再断开旧连接。删除后记得 delete。' },

    { type:'sub', title:'双向链表（Doubly Linked List）' },
    { type:'code', title:'双向链表', content:'struct DNode {\n    int data;\n    DNode* prev;\n    DNode* next;\n    DNode(int d) : data(d), prev(nullptr), next(nullptr) {}\n};\n\n// 插入操作：在 p 后面插入 newNode\n// newNode->next = p->next\n// newNode->prev = p\n// if (p->next) p->next->prev = newNode\n// p->next = newNode\n\n// 删除操作：删除 p 的后继节点 q\n// p->next = q->next\n// if (q->next) q->next->prev = p\n// delete q' },
    
    { type:'sub', title:'循环链表（Circular Linked List）' },
    { type:'para', content:'循环链表的最后一个节点指向头节点（或第一个节点），形成环状。单向/双向链表都可以做成循环的。' },
    { type:'code', title:'循环链表遍历', content:'// 循环单向链表：最后一个节点的next指向头节点\nNode* cur = head;\nif (cur != nullptr) {\n    do {\n        cout << cur->data << " ";\n        cur = cur->next;\n    } while (cur != head);  // 回到头节点时结束\n}' },
    { type:'warning', content:'循环链表遍历时要注意无限循环！一定要有终止条件（回到头节点或计数达到节点数）。' },

    { type:'section', title:'5️⃣ 数组模拟链表（静态链表）' },
    { type:'para', content:'信奥赛中常用数组模拟链表——不用 new/delete，速度快、好调试。每个节点有一个数据域和"指针域"（实际是下标索引）。' },
    { type:'code', title:'数组模拟单向链表', content:'const int N = 100010;\nint e[N];     // 数据\nint ne[N];    // next下标\nint head = -1;// 头节点下标，-1表示空\nint idx = 0;  // 当前可用位置\n\n// 头插\nvoid addToHead(int x) {\n    e[idx] = x;\n    ne[idx] = head;\n    head = idx++;\n}\n\n// 在第 k 个插入的节点后面插入 x\nvoid add(int k, int x) {\n    e[idx] = x;\n    ne[idx] = ne[k];\n    ne[k] = idx++;\n}\n\n// 删除第 k 个插入的节点后面的节点\nvoid remove(int k) {\n    ne[k] = ne[ne[k]];\n}\n\n// 遍历\nfor (int i = head; i != -1; i = ne[i])\n    cout << e[i] << " ";' },

    { type:'section', title:'6️⃣ 二叉树（Binary Tree）' },
    { type:'para', content:'二叉树是每个节点最多有两个子树的树结构，分别称为左子树和右子树。' },
    { type:'sub', title:'二叉树节点定义' },
    { type:'code', title:'二叉树节点', content:'struct TreeNode {\n    int val;\n    TreeNode* left;\n    TreeNode* right;\n    TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}\n};\n\n// 构建一棵简单的二叉树\n//       1\n//      / \\\n//     2   3\n//    / \\\n//   4   5\nTreeNode* root = new TreeNode(1);\nroot->left = new TreeNode(2);\nroot->right = new TreeNode(3);\nroot->left->left = new TreeNode(4);\nroot->left->right = new TreeNode(5);' },

    { type:'sub', title:'二叉树的四种遍历方式' },
    { type:'para', content:'遍历二叉树是指按照某种规则访问树中的所有节点。主要有以下四种方式：' },
    { type:'table', headers:['遍历方式','访问顺序','递归口诀','第一个节点'], rows:[
      ['先序遍历（前序）','根 → 左 → 右','根左右','根节点'],
      ['中序遍历','左 → 根 → 右','左根右','最左下的节点'],
      ['后序遍历','左 → 右 → 根','左右根','最左下的节点'],
      ['层序遍历','从上到下，从左到右','队列','根节点'],
    ]},
    { type:'code', title:'递归遍历', content:'// 先序遍历：根左右\nvoid preorder(TreeNode* r) {\n    if (r == nullptr) return;\n    cout << r->val << " ";   // 访问根\n    preorder(r->left);       // 遍历左子树\n    preorder(r->right);      // 遍历右子树\n}\n// 输出：1 2 4 5 3\n\n// 中序遍历：左根右\nvoid inorder(TreeNode* r) {\n    if (r == nullptr) return;\n    inorder(r->left);\n    cout << r->val << " ";\n    inorder(r->right);\n}\n// 输出：4 2 5 1 3\n\n// 后序遍历：左右根\nvoid postorder(TreeNode* r) {\n    if (r == nullptr) return;\n    postorder(r->left);\n    postorder(r->right);\n    cout << r->val << " ";\n}\n// 输出：4 5 2 3 1' },
    { type:'code', title:'层序遍历（BFS）——用队列', content:'void levelOrder(TreeNode* root) {\n    if (root == nullptr) return;\n    queue<TreeNode*> q;\n    q.push(root);\n    \n    while (!q.empty()) {\n        TreeNode* node = q.front(); q.pop();\n        cout << node->val << " ";\n        \n        if (node->left)  q.push(node->left);\n        if (node->right) q.push(node->right);\n    }\n}\n// 输出：1 2 3 4 5' },
    { type:'warning', content:'面试/笔试必考：给定一棵树，写出四种遍历的结果，或给出先序+中序还原整棵树。2023 CSP-J 初赛就考了！' },
    { type:'sub', title:'根据遍历序列还原二叉树' },
    { type:'para', content:'已知先序 + 中序 或 后序 + 中序 可以唯一确定一棵二叉树。方法是：' },
    { type:'bullet', items:[
      '先序的第一个节点 / 后序的最后一个节点 = 根节点',
      '在中序中找到根节点，左边是左子树中序，右边是右子树中序',
      '根据左右子树大小，在先序/后序中划分出左右子树的遍历序列',
      '递归处理左右子树',
    ]},

    { type:'section', title:'7️⃣ 完全二叉树编号规律 ⭐' },
    { type:'para', content:'完全二叉树（Complete Binary Tree）是信奥赛的必考知识点！它的核心是"除了最后一层，上面都是满的，最后一层节点靠左排列"。' },
    { type:'para', content:'如果我们给完全二叉树的节点按层序编号（从1开始），那么：' },
    { type:'code', title:'完全二叉树编号规律', content:'// 编号规律（非常重要！）\n//\n//          ①             第1层：1个节点\n//        /   \\\n//       ②     ③          第2层：2个节点\n//      / \\   / \\\n//     ④  ⑤  ⑥  ⑦        第3层：4个节点\n//    / \\  /\n//   ⑧ ⑨ ⑩                第4层：...\n\n// 核心规律（根节点编号为1）：\n// 节点 i 的左子节点： 2 * i\n// 节点 i 的右子节点： 2 * i + 1\n// 节点 i 的父节点：   i / 2（向下取整）\n\n// 示例：\n// 节点5的左子 = 2*5 = 10 ✓\n// 节点5的右子 = 2*5+1 = 11（不存在，因为树只有10个节点）\n// 节点10的父 = 10/2 = 5 ✓\n// 节点7的父 = 7/2 = 3 ✓' },
    { type:'tip', content:'记忆技巧：左子=2i（乘以2），右子=2i+1（乘以2再加1），父=i/2（整除2）。这个规律不仅在二叉树中用，也是堆排序的实现基础！' },
    { type:'sub', title:'完全二叉树的重要性质' },
    { type:'bullet', items:[
      '深度为 k 的完全二叉树，前 k-1 层是满二叉树（共 2^{k-1}-1 个节点）',
      '节点总数为 n 的完全二叉树，深度为 ⌊log₂n⌋ + 1',
      '叶子节点只可能在倒数两层出现',
      '节点 i 的层数为 ⌊log₂i⌋ + 1（根节点在第1层）',
      '当 2*i > n 时，节点 i 没有左孩子（即 i 是叶子节点）',
    ]},
    { type:'warning', content:'CSP-J/S 高频考题：已知完全二叉树节点总数 n，求某个编号的父/子/层数、或判断是否为叶子节点。务必熟练掌握 2i、2i+1、i/2 这三个公式！' },

    { type:'section', title:'8️⃣ 堆（Heap）——完全二叉树的经典应用' },
    { type:'para', content:'堆是一种特殊的完全二叉树，满足"堆序性"：大根堆：任意节点 ≥ 子节点（最大值在堆顶）；小根堆：任意节点 ≤ 子节点（最小值在堆顶）。' },
    { type:'sub', title:'用数组表示堆' },
    { type:'code', title:'堆的存储', content:'// 利用完全二叉树编号规律，用数组存堆\nint heap[100010];  // 从下标1开始存\nint n = 0;         // 当前堆的大小\n\n// 堆顶：heap[1]\n// 左子：heap[2*i]\n// 右子：heap[2*i+1]\n// 父：heap[i/2]' },
    { type:'sub', title:'堆的核心操作——上浮和下沉' },
    { type:'code', title:'小根堆的实现', content:'// 小根堆（最小值在堆顶）\n\n// 上浮：新插入的元素向上调整\nvoid swim(int i) {\n    while (i > 1 && heap[i] < heap[i/2]) {\n        swap(heap[i], heap[i/2]);\n        i /= 2;\n    }\n}\n\n// 下沉：堆顶被替换后向下调整\nvoid sink(int i) {\n    while (2 * i <= n) {\n        int j = 2 * i;  // 左子\n        // 如果右子存在且更小，选右子\n        if (j + 1 <= n && heap[j+1] < heap[j])\n            j = j + 1;\n        if (heap[i] <= heap[j]) break;  // 已经满足堆序\n        swap(heap[i], heap[j]);\n        i = j;\n    }\n}\n\n// 插入\nvoid push(int x) {\n    heap[++n] = x;\n    swim(n);\n}\n\n// 弹出堆顶\nvoid pop() {\n    heap[1] = heap[n--];\n    sink(1);\n}\n\n// 取堆顶\nint top() {\n    return heap[1];\n}' },
    { type:'tip', content:'大根堆和小根堆的代码几乎一样，只是比较方向反过来。大根堆要求 parent ≥ child，小根堆要求 parent ≤ child。' },
    { type:'sub', title:'建堆与堆排序' },
    { type:'code', title:'堆排序', content:'// 原地建堆（从最后一个非叶节点开始下沉）\nfor (int i = n/2; i >= 1; i--)\n    sink(i);\n\n// 堆排序（大根堆）\n// 1. 建立大根堆\n// 2. 每次把堆顶（最大值）和最后一个元素交换\n// 3. 堆大小减一，重新下沉恢复堆序\n\n// for (int i = n; i > 1; i--) {\n//     swap(heap[1], heap[i]);\n//     n--;\n//     sink(1);\n// }\n// 结果：heap[1..n] 升序排列\n\n// ⚠️ 上面只是伪代码逻辑，排序时堆排序操作省略细节\n// 实际STL中可以直接用 priority_queue' },
    { type:'table', headers:['操作','复杂度','说明'], rows:[
      ['push（插入）','O(log n)','在末尾插入后上浮'],
      ['pop（删除堆顶）','O(log n)','用最后一个元素替换堆顶后下沉'],
      ['top（取堆顶）','O(1)','直接访问 array[1]'],
      ['建堆','O(n)','从 n/2 到 1 依次下沉'],
      ['堆排序','O(n log n)','n次pop操作'],
    ]},
    { type:'warning', content:'完全二叉树编号规律 + 堆是信奥赛的超级重点！2023 CSP-J/S 初赛均有大题考查堆的调整过程和完全二叉树性质。务必吃透！' },

    { type:'section', title:'9️⃣ 图（Graph）' },
    { type:'para', content:'图由顶点（Vertex）和边（Edge）组成，记为 G=(V, E)。边可以是有向的（有向图）或无向的（无向图），也可以有权重（带权图）。' },
    
    { type:'sub', title:'图的存储方式' },
    { type:'para', content:'两种最常用的存储方式：邻接矩阵（适合稠密图）和邻接表（适合稀疏图）。' },
    { type:'table', headers:['对比','邻接矩阵','邻接表'], rows:[
      ['存储方式','二维数组 G[i][j]','vector<int> G[N]'],
      ['判断(i,j)是否有边','O(1)','O(degree)'],
      ['遍历所有邻接点','O(n)','O(degree)'],
      ['空间复杂度','O(n²)','O(n + m)'],
      ['适用场景','稠密图（m ≈ n²）','稀疏图（m << n²）'],
    ]},
    { type:'code', title:'邻接矩阵', content:'// 无向图\nconst int N = 1005;\nint g[N][N] = {0};  // g[i][j]=1 表示 i 到 j 有边\n\n// 添加边 (a, b)\nvoid addEdge(int a, int b) {\n    g[a][b] = 1;\n    g[b][a] = 1;  // 无向图需要双向\n}\n\n// 检查 a 和 b 是否有边\nif (g[a][b]) cout << "有边" << endl;\n\n// 遍历 a 的所有邻接点\nfor (int i = 1; i <= n; i++) {\n    if (g[a][i])\n        cout << i << " ";\n}' },
    { type:'code', title:'邻接表', content:'const int N = 100005;\nvector<int> adj[N];  // adj[i] 存储所有与 i 相邻的节点\n\n// 添加无向边 (a, b)\nvoid addEdge(int a, int b) {\n    adj[a].push_back(b);\n    adj[b].push_back(a);\n}\n\n// 遍历 a 的所有邻接点\nfor (int v : adj[a])\n    cout << v << " ";\n\n// 带权图\nvector<pair<int,int>> weighted[N];\n// weighted[a].push_back({b, w});  // b是邻接点，w是权重' },

    { type:'sub', title:'图的遍历——DFS（深度优先搜索）' },
    { type:'para', content:'DFS 用递归（或栈）实现，沿着一条路径走到黑，回溯后再探索下一条。' },
    { type:'code', title:'DFS 遍历图', content:'bool visited[N];\n\nvoid dfs(int u) {\n    visited[u] = true;\n    cout << u << " ";          // 访问当前节点\n    \n    for (int v : adj[u]) {     // 遍历所有邻接点\n        if (!visited[v])\n            dfs(v);\n    }\n}\n\n// 从节点1开始DFS\ndfs(1);\n\n// ⚠️ 如果是非连通图，需要遍历所有节点\nfor (int i = 1; i <= n; i++)\n    if (!visited[i]) dfs(i);' },
    { type:'tip', content:'DFS 和前面二叉树的先序遍历本质相同——都是"深入优先"。不同之处在于图可能有环，所以需要 visited 数组标记已访问节点，防止死循环。' },
    { type:'sub', title:'图的遍历——BFS（广度优先搜索）' },
    { type:'para', content:'BFS 用队列实现，按距离从近到远逐层访问。可以求无权图的最短路径。' },
    { type:'code', title:'BFS 遍历图', content:'void bfs(int start) {\n    queue<int> q;\n    bool visited[N] = {false};\n    int dist[N];  // 记录到起点的最短距离\n    fill(dist, dist + N, -1);\n    \n    visited[start] = true;\n    dist[start] = 0;\n    q.push(start);\n    \n    while (!q.empty()) {\n        int u = q.front(); q.pop();\n        cout << u << " ";  // 访问当前节点\n        \n        for (int v : adj[u]) {\n            if (!visited[v]) {\n                visited[v] = true;\n                dist[v] = dist[u] + 1;  // 距离+1\n                q.push(v);\n            }\n        }\n    }\n}' },
    { type:'table', headers:['对比','DFS','BFS'], rows:[
      ['思想','递归/栈：沿着一条路走到黑','队列：逐层扩展'],
      ['空间','O(h)，h为深度','O(w)，w为宽度（通常更大）'],
      ['最短路径','一般不能','无权图可以'],
      ['典型应用','拓扑排序、连通分量','最短路径、层次遍历'],
      ['实现方式','递归/显式栈','队列'],
    ]},

    { type:'section', title:'🔟 数据结构选择——实战建议' },
    { type:'para', content:'信奥赛解题时，选择合适的数据结构至关重要：' },
    { type:'table', headers:['需要做什么','推荐数据结构'], rows:[
      ['维护动态数组，下标访问','vector'],
      ['后进先出操作','stack / 数组模拟栈'],
      ['先进先出操作、BFS','queue / 数组模拟队列'],
      ['始终取最大/最小值','priority_queue（堆）'],
      ['按键值快速查找','map / unordered_map'],
      ['去重 + 排序','set'],
      ['频繁在中间插入/删除','list / 数组模拟链表'],
      ['层次关系、查找快','二叉树 / BST'],
      ['存储图、遍历','邻接表（大多数情况）'],
    ]},

    { type:'section', title:'📌 CSP-J/S 常考题型' },
    { type:'quiz', items:[
      { q:'栈的特点是？', options:['先进先出','先进后出','随机访问','排序存储'], answer:1 },
      { q:'完全二叉树中，节点 i 的左子节点编号是？', options:['i+1','2*i','2*i+1','i/2'], answer:1, explain:'左子 = 2 * i（根节点编号从1开始）。' },
      { q:'小根堆的堆顶元素是？', options:['最大值','最小值','中间值','随机值'], answer:1 },
      { q:'队列（Queue）的插入操作发生在一端，删除操作发生在另一端。这称为？', options:['LIFO','FIFO','随机访问','分治'], answer:1 },
      { q:'下列哪种遍历属于二叉树的"左→根→右"顺序？', options:['先序遍历','中序遍历','后序遍历','层序遍历'], answer:1 },
      { q:'在完全二叉树中，节点7的父节点编号是？', options:['3','14','4','8'], answer:0, explain:'父节点 = i/2 = 7/2 = 3。' },
      { q:'图的邻接表适用于什么类型的图？', options:['稠密图','稀疏图','必须是树','必须是完全图'], answer:1, explain:'邻接表空间 O(n+m)，适合稀疏图；稠密图用邻接矩阵 O(n²)。' },
      { q:'堆删除堆顶元素的时间复杂度是？', options:['O(1)','O(log n)','O(n)','O(n log n)'], answer:1 },
      { q:'有 n 个节点的完全二叉树，深度为？', options:['n/2','log₂n','⌊log₂n⌋ + 1','2n'], answer:2 },
      { q:'以下哪个不是图的遍历算法？', options:['DFS','BFS','Dijkstra','以上都是图的遍历'], answer:3, explain:'Dijkstra是最短路径算法，不是遍历算法。DFS和BFS才是图的两种基本遍历方式。' },
    ]},
  ]
};
